### ISSUE TITLE
运行main.py报错lxml.etree.XMLSyntaxError

### ISSUE THREAD

**Issue by ch8936** [jhao104/proxy_pool#100]
2017-12-21 00:28:15,724 ProxyManager.py[line:47] INFO freeProxySecond: fetch proxy 180.248.49.91:8080
2017-12-21 00:28:15,724 ProxyManager.py[line:47] INFO freeProxySecond: fetch proxy 87.244.35.22:8080
2017-12-21 00:28:15,724 ProxyManager.py[line:47] INFO freeProxySecond: fetch proxy 202.158.20.189:8091
Process RefreshRun:
Traceback (most recent call last):
  File "D:\Program Files\Python35\lib\multiprocessing\process.py", line 249, in _bootstrap
    self.run()
  File "D:\Program Files\Python35\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "..\Schedule\ProxyRefreshSchedule.py", line 97, in run
    main()
  File "..\Schedule\ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "..\Manager\ProxyManager.py", line 45, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "..\ProxyGetter\getFreeProxy.py", line 84, in freeProxyThird
    html_tree = getHtmlTree(url)
  File "..\Util\utilFunction.py", line 72, in getHtmlTree
    return etree.HTML(html)
  File "src\lxml\lxml.etree.pyx", line 3161, in lxml.etree.HTML (src\lxml\lxml.etree.c:78431)
  File "src\lxml\parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src\lxml\lxml.etree.c:118321)
  File "src\lxml\parser.pxi", line 1736, in lxml.etree._parseDoc (src\lxml\lxml.etree.c:117001)
  File "src\lxml\parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src\lxml\lxml.etree.c:111245)
  File "src\lxml\parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src\lxml\lxml.etree.c:105089)
  File "src\lxml\parser.pxi", line 706, in lxml.etree._handleParseResult (src\lxml\lxml.etree.c:106797)
  File "src\lxml\parser.pxi", line 644, in lxml.etree._raiseParseError (src\lxml\lxml.etree.c:105854)
  File "<string>", line 644
lxml.etree.XMLSyntaxError: line 644: b"htmlParseEntityRef: expecting ';'"

**Comment by ch8936** [comment]
windows10环境，python3.5.2,Redis端口已正确配置，相关依赖包已正确安装。

**Comment by jhao104** [comment]
@ch8936  注意看你的报错信息，
```
for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
File "..\ProxyGetter\getFreeProxy.py", line 84, in freeProxyThird
html_tree = getHtmlTree(url)
File "..\Util\utilFunction.py", line 72, in getHtmlTree
```

这说明freeProxyThird这个代理抓取方法出了问题，可能是网页变了吧，在`ProxyGetter`里面可以单独运行它。不想搞就注释掉就行

**Comment by ch8936** [comment]
感谢，已解决
