### ISSUE TITLE
pkg_resources.DistributionNotFound: APScheduler

### ISSUE THREAD

**Issue by cyjaysun** [jhao104/proxy_pool#101]
centos下python2.7运行main.py时报错如题。
Traceback (most recent call last):
  File "main.py", line 23, in <module>
    from Schedule.ProxyRefreshSchedule import run as RefreshRun
  File "../Schedule/ProxyRefreshSchedule.py", line 21, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "/usr/local/lib/python2.7/site-packages/apscheduler/__init__.py", line 2, in <module>
    release = __import__('pkg_resources').get_distribution('APScheduler').version.split('-')[0]
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 298, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 177, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 654, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/lib/python2.7/site-packages/distribute-0.6.14-py2.7.egg/pkg_resources.py", line 552, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: APScheduler

**Comment by cyjaysun** [comment]
已解决，方法如下：
编辑文件/usr/local/lib/python(你的python版本)/dist-packages/apscheduler/__init__.py
# These will be removed in APScheduler 4.0.
#release = __import__('pkg_resources').get_distribution('APScheduler').version.split('-')[0]
#version_info = tuple(int(x) if x.isdigit() else x for x in release.split('.'))
#version = __version__ = '.'.join(str(x) for x in version_info[:3])
手动改为：
**release = (3,2,0)
version_info = '3.2.0'
version = '3.2.0'**

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
