### ISSUE TITLE
lxml.etree.XMLSyntaxError: htmlParseEntityRef: expecting ';', line xx, column xx

### ISSUE THREAD

**Issue by cyjaysun** [jhao104/proxy_pool#102]
出现如题报错的解决办法：
添加Util/utilFunction.py 中getHtmlTree函数的异常处理：
html = wr.get(url=url, header=header).content
    try:
        return etree.HTML(html)
    except Exception,e:
        print e
        return 0

**Comment by xayyuu** [comment]
遇见类似的错误：
`ProcessRefreshRun:
Traceback (most recent call last):
  File "/usr/lib/python3.5/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/lib/python3.5/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 97, in run
    main()
  File "../Schedule/ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 45, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "../ProxyGetter/getFreeProxy.py", line 84, in freeProxyThird
    html_tree = getHtmlTree(url)
  File "../Util/utilFunction.py", line 72, in getHtmlTree
    return etree.HTML(html)
  File "src/lxml/lxml.etree.pyx", line 3161, in lxml.etree.HTML (src/lxml/lxml.etree.c:78444)
  File "src/lxml/parser.pxi", line 1848, in lxml.etree._parseMemoryDocument (src/lxml/lxml.etree.c:118334)
  File "src/lxml/parser.pxi", line 1736, in lxml.etree._parseDoc (src/lxml/lxml.etree.c:117014)
  File "src/lxml/parser.pxi", line 1102, in lxml.etree._BaseParser._parseDoc (src/lxml/lxml.etree.c:111258)
  File "src/lxml/parser.pxi", line 595, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:105102)
  File "src/lxml/parser.pxi", line 706, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:106810)
  File "src/lxml/parser.pxi", line 644, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:105867)
  File "<string>", line 641
lxml.etree.XMLSyntaxError: line 641: b"htmlParseEntityRef: expecting ';'"
`

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
