### ISSUE TITLE
将程序部署到服务器上，开始的是后没问题，后来的时候api就无法访问了

### ISSUE THREAD

**Issue by 631086083** [jhao104/proxy_pool#105]
Traceback (most recent call last):
  File "E:\anaconda\lib\site-packages\urllib3\connection.py", line 141, in _new_conn
    (self.host, self.port), self.timeout, **extra_kw)
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 83, in create_connection
    raise err
  File "E:\anaconda\lib\site-packages\urllib3\util\connection.py", line 73, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

**Comment by jf2000wh** [comment]
使用gevent+flask启动，或者使用nginx作为代理，纯flask性能太差

**Comment by jhao104** [comment]
@jf2000wh 确实是，生产环境flask前面得套一层东西。 推荐gunicorn

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video

**Comment by YumeMichi** [comment]
@luaaaa 你tm有毛病吗
