### ISSUE TITLE
使用问题

### ISSUE THREAD

**Issue by sksweet** [jhao104/proxy_pool#14]
作者大大：
        你好，下载了你的作品，在linux运行起来了，但只提供给我的程序不到几分钟的Ip地址，后面，proxyApi就开始报500错误，不再提供Ip地址了。这是为什么呢？下面是proxyApi报的Log。

...................................
         ValueError: View function did not return a response
127.0.0.1 - - [22/Jan/2017 17:07:58] "GET /get/ HTTP/1.1" 500 -
[2017-01-22 17:07:59,348] ERROR in app: Exception on /get/ [GET]
Traceback (most recent call last):
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
response = self.full_dispatch_request()
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1642, in full_dispatch_request
response = self.make_response(rv)
File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1731, in make_response
raise ValueError('View function did not return a response')
ValueError: View function did not return a response
127.0.0.1 - - [22/Jan/2017 17:07:59] "GET /get/ HTTP/1.1" 500 -

**Comment by sksweet** [comment]
ValueError: View function did not return a response
127.0.0.1 - - [22/Jan/2017 17:07:58] "GET /get/ HTTP/1.1" 500 -
[2017-01-22 17:07:59,348] ERROR in app: Exception on /get/ [GET]
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
127.0.0.1 - - [22/Jan/2017 17:07:59] "GET /get/ HTTP/1.1" 500 -

**Comment by jhao104** [comment]
你是哪种代理需要比较高的程序吗？
有可能是免费代理被消耗完了，你可以在ssdb里查useful_proxy_queue这个队列是否是为空的。

**Comment by jhao104** [comment]
默认是get一个代理就删除一个 。你可以修改https://github.com/jhao104/proxy_pool/blob/master/Manager/ProxyManager.py这个文件的54行，将pop()换为get()。这样就不会删除，在发现代理无效后调用delete的api

**Comment by sksweet** [comment]
作者大大：

      感谢哪么快回复，原来程序是用一个删除一个的呀，现在知道了。

谢谢。
