### ISSUE TITLE
windows报错UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal mu ltibyte sequence

### ISSUE THREAD

**Issue by pythoner-Alan-lee** [jhao104/proxy_pool#140]
Process RefreshRun:
Traceback (most recent call last):
  File "F:\python3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "F:\python3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "..\Schedule\ProxyRefreshSchedule.py", line 97, in run
    main()
  File "..\Schedule\ProxyRefreshSchedule.py", line 77, in main
    p = ProxyRefreshSchedule()
  File "..\Schedule\ProxyRefreshSchedule.py", line 40, in __init__
    ProxyManager.__init__(self)
  File "..\Manager\ProxyManager.py", line 32, in __init__
    self.db = DbClient()
  File "..\DB\DbClient.py", line 58, in __init__
    self.config = GetConfig()
  File "..\Util\GetConfig.py", line 30, in __init__
    self.config_file.read(self.config_path)
  File "F:\python3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "F:\python3\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal mu
ltibyte sequence
Process ProxyApiRun:
Traceback (most recent call last):
  File "F:\python3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "F:\python3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "..\Api\ProxyApi.py", line 88, in run
    config = GetConfig()
  File "..\Util\GetConfig.py", line 30, in __init__
    self.config_file.read(self.config_path)
  File "F:\python3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "F:\python3\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal mu
ltibyte sequence
Process ValidRun:
Traceback (most recent call last):
  File "F:\python3\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "F:\python3\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "..\Schedule\ProxyValidSchedule.py", line 71, in run
    p = ProxyValidSchedule()
  File "..\Schedule\ProxyValidSchedule.py", line 31, in __init__
    ProxyManager.__init__(self)
  File "..\Manager\ProxyManager.py", line 32, in __init__
    self.db = DbClient()
  File "..\DB\DbClient.py", line 58, in __init__
    self.config = GetConfig()
  File "..\Util\GetConfig.py", line 30, in __init__
    self.config_file.read(self.config_path)
  File "F:\python3\lib\configparser.py", line 697, in read
    self._read(fp, filename)
  File "F:\python3\lib\configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
UnicodeDecodeError: 'gbk' codec can't decode byte 0xbf in position 2: illegal mu
ltibyte sequence

不知道怎么解决，用了encoding="utf-8"也不行

**Comment by pythoner-Alan-lee** [comment]
试了一下，删了Config.ini里的中文也是不行，附上我配置的Config.ini
;[DB]
;Configure the database information
;type: SSDB/REDIS/MONGODB if use redis, only modify the host port，the type should be SSDB
type = SSDB
host = localhost
port = 6379
;port = 8888
name = proxy

;[ProxyGetter]
;register the proxy getter function
freeProxyFirst  = 1
freeProxySecond = 1
;freeProxyThird  = 1
freeProxyFourth = 1
freeProxyFifth  = 1
freeProxySixth = 1
freeProxySeventh = 1
freeProxyEight = 1
;foreign website, outside the wall
;freeProxyWallFirst = 1
;freeProxyWallSecond = 1

;[HOST]
ip = 127.0.0.1
port = 5010

**Comment by jhao104** [comment]
@pythoner-Alan-lee  你的Config.ini文件是不是用windows自带文本编辑器打开过?  
你用其他文本编辑器打开看看编码
![image](https://user-images.githubusercontent.com/15058920/39222338-cafda438-486e-11e8-9be3-be5ddc2d3f83.png)

如果用win自带的文本编辑器打开过会变成UTF-8+,转成utf-8就行了
