### ISSUE TITLE
python2.7 -m Schedule.ProxyRefreshSchedule出现OverFlowError

### ISSUE THREAD

**Issue by DataScientistSamChan** [jhao104/proxy_pool#16]
在项目目录下执行`python2.7 -m Schedule.ProxyRefreshSchedule`
出现报错：
```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/local/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/sam/app/venv/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 71, in <module>
    main()
  File "/home/sam/app/venv/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 60, in main
    p.refresh()
  File "Manager/ProxyManager.py", line 46, in refresh
    self.db.put(proxy)
  File "DB/DbClient.py", line 73, in put
    return self.client.put(value, **kwargs)
  File "/home/sam/app/venv/proxy_pool/DB/SsdbClient.py", line 62, in put
    return self.__conn.hset(self.name, value, None)
  File "/usr/local/lib/python2.7/site-packages/ssdb/client.py", line 797, in hset
    return self.execute_command('hset', name, key, value)
  File "/usr/local/lib/python2.7/site-packages/ssdb/client.py", line 218, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python2.7/site-packages/ssdb/connection.py", line 404, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python2.7/site-packages/ssdb/connection.py", line 378, in send_packed_command
    self.connect()
  File "/usr/local/lib/python2.7/site-packages/ssdb/connection.py", line 281, in connect
    sock = self._connect()
  File "/usr/local/lib/python2.7/site-packages/ssdb/connection.py", line 308, in _connect
    socket.SOCK_STREAM):
OverflowError: Python int too large to convert to C long
```

系统: CentOS6.4, 64位系统。
上网查了这个报错是因为底层用到了C的函数，导致此报错。
[http://bugs.python.org/issue21816]()
奇怪的是我在issues里没看到其他人有同样的报错。

**Comment by DataScientistSamChan** [comment]
天老爷，我的ssdf.conf的端口号是88888888888888888888888888888，怪不得会这样。

**Comment by jhao104** [comment]
还是你厉害。。。

**Comment by DataScientistSamChan** [comment]
我没用过Nosql数据库，想问一下Config.ini里面的host和name是什么？我怎么在ssdb里面设置

**Comment by jhao104** [comment]
host指ip, name在不同数据库是不一样的mongo里指dbname, ssdb里面是hashkey。你用ssdb的话可以不要用设置name
