### ISSUE TITLE
我启动后一直这个问题  然后ip存不到redis里

### ISSUE THREAD

**Issue by FlyingPigHasDream** [jhao104/proxy_pool#162]
Traceback (most recent call last):
  File "C:\Users\liaoyangjun_sx\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\liaoyangjun_sx\AppData\Local\Programs\Python\Python37\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\work\craw\proxy_pool\Schedule\ProxyRefreshSchedule.py", line 97, in run
    main()
  File "D:\work\craw\proxy_pool\Schedule\ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "D:\work\craw\proxy_pool\Manager\ProxyManager.py", line 63, in refresh
    if self.db.exists(proxy):
  File "D:\work\craw\proxy_pool\DB\DbClient.py", line 93, in exists
    return self.client.exists(key, **kwargs)

**Comment by jhao104** [comment]
@FlyingPigHasDream 是不是Config.ini配置错了 type应该是SSDB

**Comment by pblh123** [comment]
每一次运行main.py都没问题，但ssdb和redis数据库里都没有存下数据，请问怎么破

**Comment by YeClimEric** [comment]
> 每一次运行main.py都没问题，但ssdb和redis数据库里都没有存下数据，请问怎么破

没启动 redis 服务吧~

**Comment by FlyingPigHasDream** [comment]
您的邮件已经收到,会在看到第一时间回复您,祝您生活愉快。
