### ISSUE TITLE
python -m Schedule.ProxyRefreshSchedule 执行报错

### ISSUE THREAD

**Issue by jimmyleaf** [jhao104/proxy_pool#17]
```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 71, in <module>
    main()
  File "/Library/Python/2.7/site-packages/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 60, in main
    p.refresh()
  File "Manager/ProxyManager.py", line 40, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "ProxyGetter/getFreeProxy.py", line 102, in freeProxyFifth
    d = tree.xpath('.//table[@class="table"]/tbody/tr[{}]/td'.format(i + 1))[0]
IndexError: list index out of range
```
怀疑是那个代理获取源xpath有问题，尝试注释掉后，出现另外一个错误
ProxyGetter/getFreeProxy.py
```
  91     @staticmethod
  92     @robustCrawl
  93     def freeProxyFifth():
  94         """
  95         抓取guobanjia http://www.goubanjia.com/free/gngn/index.shtml
  96         :return:
  97         """
  98         url = "http://www.goubanjia.com/free/gngn/index.shtml"
  99         tree = getHtmlTree(url)
 100         # 现在每天最多放15个（一页）
 101         #for i in xrange(15):
 102             #d = tree.xpath('.//table[@class="table"]/tbody/tr[{}]/td'.format(i + 1))[0]
 103             #o = d.xpath('.//span/text() | .//div/text()')
 104             #yield ''.join(o[:-1]) + ':' + o[-1]
```

```
Traceback (most recent call last):
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/Library/Python/2.7/site-packages/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 71, in <module>
    main()
  File "/Library/Python/2.7/site-packages/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 60, in main
    p.refresh()
  File "Manager/ProxyManager.py", line 40, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
TypeError: 'NoneType' object is not iterable
```

**Comment by jhao104** [comment]
看你的报错，确实是解析代理的xpath路径发生了变化。你有兴趣的话可以尝试改下哪里的xpath。

如果你想不用这个代理网站的代理的话，应该是在Config.ini中把freeProxyFifth  = 1这一项删掉就行了。我看你这是freeProxyFifth报的错

**Comment by jimmyleaf** [comment]
3Q
确实是freeProxyFifth的错，Config.ini中注释掉freeProxyFifth = 1之后好了

**Comment by jhao104** [comment]
这个代理获取函数是可以自己任意添加删除的，你自己有好的接口就可以加进去

**Comment by twang333** [comment]
其实是因为网站禁掉了直接通过getHtmlTree来拿内容。用selenium就ok了。但是需要重写抽取部分代码。
