### ISSUE TITLE
http://127.0.0.1:5010/无法显示此页

### ISSUE THREAD

**Issue by bluesnie** [jhao104/proxy_pool#176]
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid
start byte

**Comment by jhao104** [comment]
贴详细的错误日志和你python版本
`UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid
start byte` 这个估计是你用的python2里面有什么中文字符导致

**Comment by bluesnie** [comment]
python版本是3.6的
Api下的ProxyApi.py运行出错： 
 * Serving Flask app "ProxyApi" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "ProxyApi.py", line 93, in <module>
    run()
  File "ProxyApi.py", line 89, in run
    app.run(host=config.host_ip, port=config.host_port)
  File "D:\学习软件\Python36\lib\site-packages\flask\app.py", line 943, in run
    run_simple(host, port, self, **options)
  File "D:\学习软件\Python36\lib\site-packages\werkzeug\serving.py", line 814, i
n run_simple
    inner()
  File "D:\学习软件\Python36\lib\site-packages\werkzeug\serving.py", line 774, i
n inner
    fd=fd)
  File "D:\学习软件\Python36\lib\site-packages\werkzeug\serving.py", line 660, i
n make_server
    passthrough_errors, ssl_context, fd=fd)
  File "D:\学习软件\Python36\lib\site-packages\werkzeug\serving.py", line 577, i
n __init__
    self.address_family), handler)
  File "D:\学习软件\Python36\lib\socketserver.py", line 453, in __init__
    self.server_bind()
  File "D:\学习软件\Python36\lib\http\server.py", line 138, in server_bind
    self.server_name = socket.getfqdn(host)
  File "D:\学习软件\Python36\lib\socket.py", line 673, in getfqdn
    hostname, aliases, ipaddrs = gethostbyaddr(name)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xbb in position 0: invalid
start byte

是不是这个导致http://127.0.0.1:5010/无法显示页面
