### ISSUE TITLE
AttributeError: 'str' object has no attribute 'get'

### ISSUE THREAD

**Issue by iamanam** [jhao104/proxy_pool#179]
why i am getting this error?

I am running it virtualenv using python 3.5.2

`
2018-09-23 05:35:39,588 ProxyRefreshSchedule.py[line:50] INFO ProxyRefreshSchedule: Sun Sep 23 05:35:39 2018 start validProxy
Exception in thread Thread-30:
Traceback (most recent call last):
  File "/usr/lib/python3.5/threading.py", line 914, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.5/threading.py", line 862, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 73, in refreshPool
    pp.validProxy()
  File "../Schedule/ProxyRefreshSchedule.py", line 54, in validProxy
    raw_proxy = raw_proxy_item.get('proxy')
AttributeError: 'str' object has no attribute 'get'

`

**Comment by jhao104** [comment]
@iamanam `Config.ini` file:
the DB's `type` must be `SSDB`

**Comment by iamanam** [comment]
ya, its working now. Thanks.
