### ISSUE TITLE
执行python main.py 后报错UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 106: ordinal not in range(128)

### ISSUE THREAD

**Issue by zhw520** [jhao104/proxy_pool#181]
Process ProxyApiRun:
Process RefreshRun:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Api/ProxyApi.py", line 88, in run
    config = GetConfig()
  File "../Util/GetConfig.py", line 30, in __init__
    self.config_file.read(self.config_path)
  File "/usr/local/python3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/python3/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/local/python3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 106: ordinal not in range(128)
Process ValidRun:
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 97, in run
    main()
  File "../Schedule/ProxyRefreshSchedule.py", line 77, in main
    p = ProxyRefreshSchedule()
  File "../Schedule/ProxyRefreshSchedule.py", line 40, in __init__
    ProxyManager.__init__(self)
  File "../Manager/ProxyManager.py", line 32, in __init__
    self.db = DbClient()
  File "../DB/DbClient.py", line 58, in __init__
    self.config = GetConfig()
  File "../Util/GetConfig.py", line 30, in __init__
    self.config_file.read(self.config_path)
  File "/usr/local/python3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/python3/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/local/python3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 106: ordinal not in range(128)
Traceback (most recent call last):
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/local/python3/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyValidSchedule.py", line 71, in run
    p = ProxyValidSchedule()
  File "../Schedule/ProxyValidSchedule.py", line 31, in __init__
    ProxyManager.__init__(self)
  File "../Manager/ProxyManager.py", line 32, in __init__
    self.db = DbClient()
  File "../DB/DbClient.py", line 58, in __init__
    self.config = GetConfig()
  File "../Util/GetConfig.py", line 30, in __init__
    self.config_file.read(self.config_path)
  File "/usr/local/python3/lib/python3.6/configparser.py", line 697, in read
    self._read(fp, filename)
  File "/usr/local/python3/lib/python3.6/configparser.py", line 1015, in _read
    for lineno, line in enumerate(fp, start=1):
  File "/usr/local/python3/lib/python3.6/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xef in position 106: ordinal not in range(128)

返回的错误信息是这样的，求大佬解答

**Comment by zhw520** [comment]
> 看最后一行
> 中文字符错误，你Config.ini里面写了中文吧

感谢大佬。确实是这个问题。
