### ISSUE TITLE
ValueError: Your platform does not support forking.

### ISSUE THREAD

**Issue by hiwoshixiaoyu** [jhao104/proxy_pool#197]
ValueError: Your platform does not support forking.

**Comment by neasonpy** [comment]
同问，出现了一样的问题，单独跑API下的ProxyApi.py

C:\Users\Administrator\Desktop\proxy_pool-master\Api>python ProxyApi.py
Traceback (most recent call last):
  File "ProxyApi.py", line 92, in <module>
    run()
  File "ProxyApi.py", line 88, in run
    app.run(host=config.host_ip, port=config.host_port, threaded=False, processe
s=config.processes)
  File "C:\workspace\Python3\Python37\lib\site-packages\flask\app.py", line 841,
 in run
    run_simple(host, port, self, **options)
  File "C:\workspace\Python3\Python37\lib\site-packages\werkzeug\serving.py", li
ne 708, in run_simple
    inner()
  File "C:\workspace\Python3\Python37\lib\site-packages\werkzeug\serving.py", li
ne 670, in inner
    fd=fd)
  File "C:\workspace\Python3\Python37\lib\site-packages\werkzeug\serving.py", li
ne 561, in make_server
    passthrough_errors, ssl_context, fd=fd)
  File "C:\workspace\Python3\Python37\lib\site-packages\werkzeug\serving.py", li
ne 541, in __init__
    raise ValueError('Your platform does not support forking.')
ValueError: Your platform does not support forking.

**Comment by jhao104** [comment]
https://github.com/jhao104/proxy_pool/blob/27fc9dfe4caca141c2718a32f496769c8220d83f/Api/ProxyApi.py#L88
win下面改成：
```
app.run(host=config.host_ip, port=config.host_port) 
```

**Comment by neasonpy** [comment]
> ValueError: Your platform does not support forking.



> [proxy_pool/Api/ProxyApi.py](https://github.com/jhao104/proxy_pool/blob/27fc9dfe4caca141c2718a32f496769c8220d83f/Api/ProxyApi.py#L88)
> 
> Line 88 in [27fc9df](/jhao104/proxy_pool/commit/27fc9dfe4caca141c2718a32f496769c8220d83f)
> 
>  app.run(host=config.host_ip, port=config.host_port, threaded=False, processes=config.processes) 
> 
> win下面改成：
> ```
> app.run(host=config.host_ip, port=config.host_port) 
> ```

解决了，十分感谢
