### ISSUE TITLE
我在我的vps上面配置项目但是提示werkzeug库没有，可是我已经安装过了

### ISSUE THREAD

**Issue by yasee1994** [jhao104/proxy_pool#226]
环境是anaconda的python3 跑过环境配置文件了
`Successfully installed APScheduler-3.2.0 Flask-0.12 Jinja2-2.10 MarkupSafe-1.1.0 itsdangerous-1.1.0 lxml-3.7.2 pymongo-3.7.2 pytz-2018.7 redis-3.0.1 requests-2.20.0 tzlocal-1.5.1 werkzeug-0.11.15`
也没有报错，可是当我进入Run文件夹python3 main.py 的时候却会提示缺少werkzeug
请问下这个是什么原因
```
Requirement already satisfied: werkzeug in /usr/local/lib/python3.6/dist-packages (0.11.15)
(python3) root@Yasee:/home/mine/proxy_pool/proxy_pool-master/Run# python3 main.py
Traceback (most recent call last):
  File "main.py", line 21, in <module>
    from Api.ProxyApi import run as ProxyApiRun
  File "../Api/ProxyApi.py", line 17, in <module>
    from werkzeug.wrappers import Response
ModuleNotFoundError: No module named 'werkzeug'

```

**Comment by 1again** [comment]
你直接在当前目录python 然后 `import werkzeug` 能成功吗?

**Comment by yasee1994** [comment]
```
(python3) root@Yasee:~# python3
Python 3.7.1 (default, Oct 23 2018, 19:19:42) 
[GCC 7.3.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import werkzeug
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'werkzeug'
>>> 
```
也是提示没有这个库。。
```
(python3) root@Yasee:~# pip3 list
Package             Version  
------------------- ---------
APScheduler         3.2.0    
asn1crypto          0.24.0   
attrs               17.4.0   
Automat             0.6.0    
certifi             2018.1.18
chardet             3.0.4    
click               6.7      
colorama            0.3.7    
command-not-found   0.3      
configobj           5.0.6    
constantly          15.1.0   
cryptography        2.1.4    
distro-info         0.18     
fake-useragent      0.1.11   
Flask               0.12     
httplib2            0.9.2    
hyperlink           17.3.1   
idna                2.6      
incremental         16.10.1  
itsdangerous        1.1.0    
Jinja2              2.10     
language-selector   0.1      
lxml                3.7.2    
MarkupSafe          1.1.0    
PAM                 0.4.2    
pip                 18.1     
pyasn1              0.4.2    
pyasn1-modules      0.2.1    
pygobject           3.26.1   
pymongo             3.7.2    
pyOpenSSL           17.5.0   
pyserial            3.4      
python-apt          1.6.1    
python-debian       0.1.32   
pytz                2018.7   
PyYAML              3.12     
redis               3.0.1    
requests            2.20.0   
requests-unixsocket 0.1.5    
service-identity    16.0.0   
setuptools          40.6.2   
six                 1.11.0   
ssh-import-id       5.7      
systemd-python      234      
Twisted             17.9.0   
tzlocal             1.5.1    
ufw                 0.35     
unattended-upgrades 0.1      
urllib3             1.22     
Werkzeug            0.14.1   
wheel               0.32.3   
zope.interface      4.3.2    
(python3) root@Yasee:~# 
```
我在自己的本地电脑和树莓派都配置过都是没问题的，但是就是vps上面出现这个问题。。。

**Comment by 1again** [comment]
```
import sys
print(sys.path)
```
看下相应目录下是真的有`werkzeug`模块吗?
你vps上是不是有多个python版本?

**Comment by yasee1994** [comment]
好吧已经解决了，万万没想到居然是这样的原因：
是因为我使用pip install -r requirements.txt（可是我在本地上面也都是这样安装的。。。）
然后vps上面的python环境是anaconda的虚拟环境，用上面的指令进行安装的话他自动安装到了系统内的python3中。。。（可是明明已经激活了conda里的python3。。。。）
后来手动一个个conda isntall把包都给装上就搞定了

> ```python
> import sys
> print(sys.path)
> ```
> 
> ```shell
> pip3 show Werkzeug
> ```
> 
> 看下相应目录下是真的有`werkzeug`模块吗?

**Comment by 1again** [comment]
所以让你用docker, 环境隔离, 不会发生这种事.

**Comment by yasee1994** [comment]
> 所以让你用docker, 环境隔离, 不会发生这种事.

主要自己才刚刚入门python没多久好多东西都在慢慢摸索。。。docker也只是听过，不过最近回去学习下怎么使用，还是多谢你的帮忙，要不然得折腾好久
