### ISSUE TITLE
运行main报错

### ISSUE THREAD

**Issue by Hiboboo** [jhao104/proxy_pool#237]
运行后，报这个异常。
MongoDB 版本4.0.5，数据各项配置是没问题的
Python 3.7

总是说运行`find()`方法需要认证，网上查了相关问题，说是MongoDB在3.0之后采用的是`SCRAM-SHA-1`认证方法，我查了下我的MongoDB，确实是这种的，不知道怎么配置到项目中。
```
Traceback (most recent call last):
  File "D:\Program Files\Python3.7.1\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "D:\Program Files\Python3.7.1\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "D:\Py-projects\proxy_pool\Schedule\ProxyValidSchedule.py", line 72, in run
    p.main()
  File "D:\Py-projects\proxy_pool\Schedule\ProxyValidSchedule.py", line 53, in main
    self.putQueue()
  File "D:\Py-projects\proxy_pool\Schedule\ProxyValidSchedule.py", line 65, in putQueue
    self.proxy_item = self.db.getAll()
  File "D:\Py-projects\proxy_pool\DB\DbClient.py", line 99, in getAll
    return self.client.getAll()
  File "D:\Py-projects\proxy_pool\DB\MongodbClient.py", line 51, in getAll
    return {p['proxy']: p['num'] for p in self.db[self.name].find()}
  File "D:\Py-projects\proxy_pool\DB\MongodbClient.py", line 51, in <dictcomp>
    return {p['proxy']: p['num'] for p in self.db[self.name].find()}
  File "D:\Program Files\Python3.7.1\lib\site-packages\pymongo\cursor.py", line 1189, in next
    if len(self.__data) or self._refresh():
  File "D:\Program Files\Python3.7.1\lib\site-packages\pymongo\cursor.py", line 1104, in _refresh
    self.__send_message(q)
  File "D:\Program Files\Python3.7.1\lib\site-packages\pymongo\cursor.py", line 982, in __send_message
    helpers._check_command_response(first)
  File "D:\Program Files\Python3.7.1\lib\site-packages\pymongo\helpers.py", line 155, in _check_command_response
    raise OperationFailure(msg % errmsg, code, response)
pymongo.errors.OperationFailure: command find requires authentication
2019-01-02 17:47:49,623 ProxyManager.py[line:46] INFO freeProxyFirst: fetch proxy start
```

**Comment by jhao104** [comment]
@Hiboboo mongo没有正式维护 建议使用ssdb或者redis

**Comment by fantasy-ctgu** [comment]
连接mongodb出现了问题,在代码`DB/MongodbClient.py`中直接修改22行的代码为以下可用:
`self.client = MongoClient("mongodb://root:root@localhost:27017/")`

**Comment by bybabo** [comment]
Mongo配置方法：
 MongoDB安装之后直接修改`DB/MongodbClient.py`中直接修改22行的代码为以下可用:
`self.client = MongoClient("mongodb://localhost:27017/")`    

与@fantasy-ctgu 略有不同，免去了设置Mongodb配置的繁琐，但是MongoDB存在未授权的安全隐患，谨慎采纳
Mongodb版本4.0测试可用
