### ISSUE TITLE
GetConfig 在python 3.7中报错

### ISSUE THREAD

**Issue by Jesn** [jhao104/proxy_pool#244]
`Traceback (most recent call last):
  File "F:/Localhost/GIt/github/python/proxy_pool/Util/GetConfig.py", line 65, in <module>
    config = GetConfig()
  File "F:/Localhost/GIt/github/python/proxy_pool/Util/GetConfig.py", line 29, in __init__
    self.config_file = ConfigParse(defaults={"password": None})
  File "F:\Localhost\GIt\github\python\proxy_pool\Util\utilClass.py", line 48, in __init__
    ConfigParser.__init__(self, *args, **kwargs)
  File "C:\Users\Darren\Anaconda3\lib\configparser.py", line 638, in __init__
    self._read_defaults(defaults)
  File "C:\Users\Darren\Anaconda3\lib\configparser.py", line 1216, in _read_defaults
    self.read_dict({self.default_section: defaults})
  File "C:\Users\Darren\Anaconda3\lib\configparser.py", line 753, in read_dict
    self.set(section, key, value)
  File "C:\Users\Darren\Anaconda3\lib\configparser.py", line 1197, in set
    self._validate_value_types(option=option, value=value)
  File "C:\Users\Darren\Anaconda3\lib\configparser.py", line 1182, in _validate_value_types
    raise TypeError("option values must be strings")
TypeError: option values must be strings`

建议把
`self.config_file = ConfigParse(defaults={"password": None})`
改为
`self.config_file = ConfigParse(defaults={"password": ''})`

**Comment by jhao104** [comment]
@Jesn 是滴，已经改了，代码还没推。
