### ISSUE TITLE
求解

### ISSUE THREAD

**Issue by 1019wellBegin121** [jhao104/proxy_pool#246]
D:\Pycharm工作资料\代码流\venv\Scripts\python.exe C:/Users/ThinkPad/Downloads/proxy_pool-master/Run/main.py
 * Serving Flask app "Api.ProxyApi" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
2019-02-15 17:30:38,518 ProxyManager.py[line:46] INFO freeProxyFirst: fetch proxy start
Process ValidRun:
Traceback (most recent call last):
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\connection.py", line 493, in connect
    sock = self._connect()
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\connection.py", line 550, in _connect
    raise err
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\connection.py", line 538, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\python\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "D:\python\lib\multiprocessing\process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "..\Schedule\ProxyValidSchedule.py", line 72, in run
    p.main()
  File "..\Schedule\ProxyValidSchedule.py", line 53, in main
    self.putQueue()
  File "..\Schedule\ProxyValidSchedule.py", line 65, in putQueue
    self.proxy_item = self.db.getAll()
  File "..\DB\DbClient.py", line 99, in getAll
    return self.client.getAll()
  File "C:\Users\ThinkPad\Downloads\proxy_pool-master\DB\SsdbClient.py", line 98, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\client.py", line 2649, in hgetall
    return self.execute_command('HGETALL', name)
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\client.py", line 774, in execute_command
    connection.send_command(*args)
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\connection.py", line 619, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\connection.py", line 594, in send_packed_command
    self.connect()
  File "D:\Pycharm工作资料\代码流\venv\lib\site-packages\redis\connection.py", line 498, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:8888. 由于目标计算机积极拒绝，无法连接。.
2019-02-15 17:30:40,573 ProxyManager.py[line:51] INFO freeProxyFirst: fetch proxy 95.80.254.119:8251
2019-02-15 17:30:41,580 ProxyManager.py[line:56] ERROR freeProxyFirst: fetch proxy fail
2019-02-15 17:30:41,581 ProxyManager.py[line:46] INFO freeProxySecond: fetch proxy start
2019-02-15 17:30:43,688 ProxyManager.py[line:51] INFO freeProxySecond: fetch proxy 114.249.119.238:9000
2019-02-15 17:30:44,693 ProxyManager.py[line:56] ERROR freeProxySecond: fetch proxy fail
2019-02-15 17:30:44,693 ProxyManager.py[line:46] INFO freeProxyFourth: fetch proxy start
2019-02-15 17:30:46,898 ProxyManager.py[line:51] INFO freeProxyFourth: fetch proxy 111.177.189.227:9999
2019-02-15 17:30:47,901 ProxyManager.py[line:56] ERROR freeProxyFourth: fetch proxy fail
2019-02-15 17:30:47,901 ProxyManager.py[line:46] INFO freeProxyFifth: fetch proxy start
2019-02-15 17:30:49,962 ProxyManager.py[line:51] INFO freeProxyFifth: fetch proxy 95.80.254.119:8821
2019-02-15 17:30:50,965 ProxyManager.py[line:56] ERROR freeProxyFifth: fetch proxy fail
2019-02-15 17:30:50,965 ProxyManager.py[line:46] INFO freeProxySeventh: fetch proxy start
2019-02-15 17:30:53,140 ProxyManager.py[line:51] INFO freeProxySeventh: fetch proxy 110.52.235.138:9999
2019-02-15 17:30:54,142 ProxyManager.py[line:56] ERROR freeProxySeventh: fetch proxy fail
2019-02-15 17:30:54,142 ProxyManager.py[line:46] INFO freeProxyTen: fetch proxy start
2019-02-15 17:30:54,346 ProxyManager.py[line:51] INFO freeProxyTen: fetch proxy 138.122.5.22:61201
2019-02-15 17:30:55,346 ProxyManager.py[line:56] ERROR freeProxyTen: fetch proxy fail
2019-02-15 17:30:55,347 ProxyManager.py[line:46] INFO freeProxyEleven: fetch proxy start
2019-02-15 17:30:56,009 ProxyManager.py[line:51] INFO freeProxyEleven: fetch proxy 120.76.77.152:9999
2019-02-15 17:30:57,010 ProxyManager.py[line:56] ERROR freeProxyEleven: fetch proxy fail
2019-02-15 17:30:57,011 ProxyManager.py[line:46] INFO freeProxyTwelve: fetch proxy start
2019-02-15 17:30:59,217 ProxyManager.py[line:51] INFO freeProxyTwelve: fetch proxy 114.119.116.92:8198
2019-02-15 17:31:00,218 ProxyManager.py[line:56] ERROR freeProxyTwelve: fetch proxy fail
2019-02-15 17:31:00,218 ProxyManager.py[line:46] INFO freeProxyWallFirst: fetch proxy start
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))
('Connection aborted.', ConnectionResetError(10054, '远程主机强迫关闭了一个现有的连接。', None, 10054, None))

Process finished with exit code -1

**Comment by jhao104** [comment]
数据库配置问题，连不上数据库

**Comment by zakkitao** [comment]
出现了同样的问题，我的redis卸载了重新装也配置不上。

**Comment by zakkitao** [comment]
我的解决了，谢谢。

**Comment by yierzy** [comment]
@jhao104 看好几个issue都是类似的问题，估计都是redis和容器没太用多少的朋友，能麻烦你补充说明一下这个issue的“数据库配置问题”是什么问题，哪里做错了吗？非常感谢！
我查了不少 redis 和 docker 的资料，不过还是比较晕。我说一下我的理解，不知道对不对：
这个包到本地按照说明进行部署，总体有2种方案：
1. 不用 docker，在 cli 里面 shell 开启运行，需要本地也正确安装和配置 redis
2. 用 docker，直接使用 jhao104/proxypool 的docker，但是这个 docker 里面并不包含 redis，同时还需要正确安装并配置 docker，并进行连接；或者 redis 也采用 redis docker。

**Comment by jhao104** [comment]
@yierzy 你代码里面配置的数据库地址是 `127.0.0.1:8888`  你要确认你的运行环境和 `127.0.0.1:8888` 是通的
