### ISSUE TITLE
总是提示” 由于目标计算机积极拒绝，无法连接。“

### ISSUE THREAD

**Issue by zakkitao** [jhao104/proxy_pool#259]
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\anaconda\lib\threading.py", line 917, in _bootstrap_inner
    self.run()
  File "D:\anaconda\lib\threading.py", line 865, in run
    self._target(*self._args, **self._kwargs)
  File "..\Schedule\ProxyRefreshSchedule.py", line 73, in refreshPool
    pp.validProxy()
  File "..\Schedule\ProxyRefreshSchedule.py", line 49, in validProxy
    raw_proxy_item = self.db.pop()
  File "..\DB\DbClient.py", line 96, in pop
    return self.client.pop(**kwargs)
  File "D:\proxy_pool-master\DB\SsdbClient.py", line 85, in pop
    proxies = self.__conn.hkeys(self.name)
  File "D:\anaconda\lib\site-packages\redis\client.py", line 2663, in hkeys
    return self.execute_command('HKEYS', name)
  File "D:\anaconda\lib\site-packages\redis\client.py", line 772, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "D:\anaconda\lib\site-packages\redis\connection.py", line 1142, in get_connection
    connection.connect()
  File "D:\anaconda\lib\site-packages\redis\connection.py", line 497, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:8888. 由于目标计算机积极拒绝，无法连接。.

**Comment by zakkitao** [comment]
自己的问题自己来解答吧。
还是配置问题，一定要按照介绍里面来，我是生产环境和开发环境那一步漏了。
另外记得，把docker里面的地址和port改了。

**Comment by moep0** [comment]
可以说详细一点吗，感谢
