### ISSUE TITLE
数据库更新逻辑

### ISSUE THREAD

**Issue by gumpjt** [jhao104/proxy_pool#26]
工具很有用赞一个。
几个问题想确认下：
1. get_all返回的代理list的更新逻辑是什么。好像这个List里面是越来越多的。昨天的ipA可用，今天不可用，也会返回。
2. 是否考虑加入api实现：返回过去X分钟测试过的，确定可用的代理List。

谢谢。

**Comment by jhao104** [comment]
你好，
  第一个问题是因为你的程序遇到不可用的代理时需要调用delete接口将其删掉。
  第二个问题类似，当时设想的时如果外部爬虫会一直去delete代理池，等于是爬虫回来检查代理池，所以没有考虑自己检测。
  多谢你的建议，现在已加上[固定检测](https://github.com/jhao104/proxy_pool/blob/master/Schedule/ProxyValidSchedule.py)

**Comment by gumpjt** [comment]
谢谢反馈。我是JSer，python不太会写。这两天刚准备在自己的逻辑中加入list返回判断，现在可以直接伸手咯。:bowtie

**Comment by gumpjt** [comment]
更新为最新的代码之后，好像不能正常工作了。:flushed:

**Comment by jhao104** [comment]
DB用的SSDB吗 贴下错误信息

**Comment by gumpjt** [comment]
这次更新之前，运行python -m Schedule.ProxyRefreshSchedule 之后过一会是有正常日志信息的。但更新后，没有日志，也没有其他任何信息。Ctrl+C 后打印如下信息：

`^CTraceback (most recent call last):
  File "/usr/lib/python2.7/runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
    exec code in run_globals
  File "/home/tools/test/proxy_pool/Schedule/ProxyRefreshSchedule.py", line 88, in <module>
    sched.start()
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 19, in start
    self._main_loop()
  File "/usr/local/lib/python2.7/dist-packages/apscheduler/schedulers/blocking.py", line 28, in _main_loop
    self._event.wait(wait_seconds)
  File "/usr/lib/python2.7/threading.py", line 614, in wait
    self.__cond.wait(timeout)
  File "/usr/lib/python2.7/threading.py", line 359, in wait
    _sleep(delay)
KeyboardInterrupt
`

**Comment by jhao104** [comment]
到Schedule目录下运行ProxyRefreshSchedule.py 启动方式有变动

**Comment by gumpjt** [comment]
好的 问题解决咯 可以close了！
