### ISSUE TITLE
运行环境设置都是什么？

### ISSUE THREAD

**Issue by gaoda1234** [jhao104/proxy_pool#29]
用的centos 6 python3.5 结果各种出错

[root@localhost proxy_pool-master]# python -m Schedule.ProxyRefreshSchedule
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/runpy.py", line 184, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/local/lib/python3.5/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/root/proxy_pool-master/Schedule/ProxyRefreshSchedule.py", line 19, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
ImportError: No module named 'apscheduler'

是哪里没有装好吗？

**Comment by jhao104** [comment]
现在暂时不支持py3
你是apscheduler这个包没有装。
你可以看下这个文件[](https://github.com/jhao104/proxy_pool/blob/master/requirements.txt)

**Comment by gaoda1234** [comment]
支持python什么版本？

**Comment by jhao104** [comment]
2

**Comment by gaoda1234** [comment]
Traceback (most recent call last):
  File "/usr/lib64/python2.6/runpy.py", line 122, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "/usr/lib64/python2.6/runpy.py", line 34, in _run_code
    exec code in run_globals
  File "/root/proxy_pool-master/Schedule/ProxyRefreshSchedule.py", line 19, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "/usr/lib64/python2.6/site-packages/apscheduler/schedulers/blocking.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler, STATE_STOPPED
  File "/usr/lib64/python2.6/site-packages/apscheduler/schedulers/base.py", line 177
    with self._jobstores_lock, self._executors_lock:
                             ^
SyntaxError: invalid syntax
帮忙看看这是什么错误吧，apscheduler安装好了还需要启动什么的吗？

**Comment by gaoda1234** [comment]
python2.6 和APScheduler 3.2.0 兼容吗？新手问题多，多包涵。

**Comment by jhao104** [comment]
每个三方库都有对应不同py版本的包。你下载的时候下py2版本的。如果你电脑上是py2，直接pip install 安装的就是py2对应的包
