### ISSUE TITLE
docker 报错

### ISSUE THREAD

**Issue by loveship00** [jhao104/proxy_pool#291]
Traceback (most recent call last):
  File "Run/main.py", line 21, in <module>
    from Api.ProxyApi import run as ProxyApiRun
  File "./Api/ProxyApi.py", line 22, in <module>
    from Config.ConfigGetter import config
  File "./Config/ConfigGetter.py", line 17, in <module>
    from Config.setting import *
  File "./Config/setting.py", line 92
    ]
    ^
SyntaxError: invalid syntax

**Comment by jhao104** [comment]
检查下 `/Config/setting.py` 语法都没过， 用ide看下
