### ISSUE TITLE
python2.7环境启用main.py报错

### ISSUE THREAD

**Issue by hktk200216** [jhao104/proxy_pool#312]
root@AMS:~/proxy_pool-master/Run# python main.py
INFO:werkzeug: * Running on http://0.0.0.0:5010/ (Press CTRL+C to quit)
Process ValidRun:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyValidSchedule.py", line 72, in run
    p.main()
  File "../Schedule/ProxyValidSchedule.py", line 53, in main
    self.putQueue()
  File "../Schedule/ProxyValidSchedule.py", line 65, in putQueue
    self.proxy_item = self.db.getAll()
  File "../DB/DbClient.py", line 99, in getAll
    return self.client.getAll()
  File "/root/proxy_pool-master/DB/SsdbClient.py", line 98, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 1967, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 665, in execute_command
    connection = pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 1095, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 1063, in make_connection
    connection = self.connection_class(**self.connection_kwargs)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 446, in __init__
    self.port = int(port)
ValueError: invalid literal for int() with base 10: 'proxy'
2019-07-23 16:19:11,846 ProxyManager.py[line:46] INFO freeProxy01: fetch proxy start
2019-07-23 16:19:12,019 ProxyManager.py[line:51] INFO freeProxy01: fetch proxy 49.84.158.189:53281
2019-07-23 16:19:12,020 ProxyManager.py[line:56] ERROR freeProxy01: fetch proxy fail
2019-07-23 16:19:12,021 ProxyManager.py[line:46] INFO freeProxy02: fetch proxy start
Could not find an available JavaScript runtime.
2019-07-23 16:19:12,135 ProxyManager.py[line:46] INFO freeProxy03: fetch proxy start
2019-07-23 16:19:12,518 ProxyManager.py[line:51] INFO freeProxy03: fetch proxy 1.197.204.70:9999
2019-07-23 16:19:12,520 ProxyManager.py[line:56] ERROR freeProxy03: fetch proxy fail
2019-07-23 16:19:12,520 ProxyManager.py[line:46] INFO freeProxy04: fetch proxy start
2019-07-23 16:19:12,680 ProxyManager.py[line:51] INFO freeProxy04: fetch proxy 49.84.158.189:53281
2019-07-23 16:19:12,681 ProxyManager.py[line:56] ERROR freeProxy04: fetch proxy fail
2019-07-23 16:19:12,681 ProxyManager.py[line:46] INFO freeProxy05: fetch proxy start
2019-07-23 16:19:14,963 ProxyManager.py[line:51] INFO freeProxy05: fetch proxy 221.206.100.133:54781
2019-07-23 16:19:14,964 ProxyManager.py[line:56] ERROR freeProxy05: fetch proxy fail
2019-07-23 16:19:14,964 ProxyManager.py[line:46] INFO freeProxy06: fetch proxy start
2019-07-23 16:19:15,560 ProxyManager.py[line:56] ERROR freeProxy06: fetch proxy fail
2019-07-23 16:19:15,560 ProxyManager.py[line:46] INFO freeProxy07: fetch proxy start
2019-07-23 16:19:15,787 ProxyManager.py[line:51] INFO freeProxy07: fetch proxy 58.244.193.211:8080
2019-07-23 16:19:15,788 ProxyManager.py[line:56] ERROR freeProxy07: fetch proxy fail
2019-07-23 16:19:15,788 ProxyManager.py[line:46] INFO freeProxy08: fetch proxy start
2019-07-23 16:19:16,269 ProxyManager.py[line:51] INFO freeProxy08: fetch proxy 183.63.101.62:55555
2019-07-23 16:19:16,269 ProxyManager.py[line:56] ERROR freeProxy08: fetch proxy fail
2019-07-23 16:19:16,270 ProxyManager.py[line:46] INFO freeProxy09: fetch proxy start
2019-07-23 16:19:17,463 ProxyManager.py[line:51] INFO freeProxy09: fetch proxy 61.183.176.122:57210
2019-07-23 16:19:17,464 ProxyManager.py[line:56] ERROR freeProxy09: fetch proxy fail

**Comment by jhao104** [comment]
@hktk200216 数据库端口配错了

**Comment by hktk200216** [comment]
@jhao104 重新配置，一切正常了，感谢！！
