### ISSUE TITLE
DB\MongodbClient.py中的clean方法应改成clear

### ISSUE THREAD

**Issue by kite8** [jhao104/proxy_pool#326]
大佬你好，DB\MongodbClient.py中的方法名字clean有问题，应该是clear
```python
# file path : Config/settings.py

# 修改type
PY3 = sys.version_info >= (3,)
DB_TYPE = getenv('db_type', 'MONGODB').upper()
DB_HOST = getenv('db_host', '127.0.0.1')
DB_PORT = getenv('db_port', 27017)
DB_PASSWORD = getenv('db_password', '')

# 注释掉了checkConfig()
```
python proxyPool.py schedule
```
Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\ProgramData\Anaconda3\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "..\Schedule\ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "..\Schedule\ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "..\Schedule\RawProxyCheck.py", line 67, in doRawProxyCheck
    pm.db.clear()
  File "..\DB\DbClient.py", line 105, in clear
    return self.client.clear()
AttributeError: 'MongodbClient' object has no attribute 'clear'
```

**Comment by jhao104** [comment]
看文档，master分支上的版本 mongodb暂不支持， 要用的化下老版本

**Comment by kite8** [comment]
> 看文档，master分支上的版本 mongodb暂不支持， 要用的化下老版本

好的，谢谢大佬，那我就暂时不merge到自己的master, 主要是我自己电脑是win，如果是linux，我就安装一个ssdb了，我看了ssdb官网的文档，win最好安装一个虚拟机，然后再用
