### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by pearandli** [jhao104/proxy_pool#331]
在执行python proxypool.py schedule时运行会报错，
`Exception in thread thread_6:
Traceback (most recent call last):
  File "C:\Python36\lib\threading.py", line 916, in _bootstrap_inner
    self.run()
  File "..\Schedule\RawProxyCheck.py", line 44, in run
    proxy_obj = Proxy.newProxyFromJson(proxy_json)
  File "..\ProxyHelper\Proxy.py", line 39, in newProxyFromJson
    return cls(proxy=proxy_dict.get("proxy", ""),
AttributeError: 'int' object has no attribute 'get'`

**Comment by jhao104** [comment]
你是不是从老版本升上来的，把之前的数据库的数据清空再跑
