### ISSUE TITLE
运行python proxyPool.py schedule  报错：Error 111 connecting to 127.0.0.1:8888. Connection refused.

### ISSUE THREAD

**Issue by zhengdafangyuan** [jhao104/proxy_pool#343]
运行环境：  Ubuntu 16.04.6,  python 3.6
成功安装 requirements.txt 依赖包后， 配置Config/setting.py 后，运行报错。

**然后运行 python proxyPool.py schedule, 出现如下报错：**
**ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused**
这是数据库没有设置对吗？还是端口或者本地监控地址问题？

**配置Config/setting.py**
`
DB_TYPE = getenv('db_type', 'SSDB').upper()
DB_HOST = getenv('db_host', '127.0.0.1')
DB_PORT = getenv('db_port', '8888')
DB_PASSWORD = getenv('db_password', '')

""" 数据库配置 """
DATABASES = {
    "default": {
        "TYPE": 'SSDB',
        "HOST": '127.0.0.1',
        "PORT": 8888,
        "NAME": "proxy",
        "PASSWORD": ''
    }
}
# register the proxy getter function
PROXY_GETTER = [
    "freeProxy01",
    "freeProxy02",
    "freeProxy03",
    "freeProxy04",
    "freeProxy05",
    "freeProxy06",
    "freeProxy07",
    "freeProxy08",
    "freeProxy09",
]

""" API config http://127.0.0.1:5010 """
SERVER_API = {
    "HOST": "0.0.0.0",  # The ip specified which starting the web API
    "PORT": 5010  # port number to which the server listens to
}
`

**然后运行 python proxyPool.py schedule, 出现如下报错：**
**ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused**
****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2019-08-30 10:38:33,526 ProxyScheduler.py[line:33] INFO start fetch proxy
2019-08-30 10:38:33,527 ProxyManager.py[line:44] INFO ProxyFetch : start
2019-08-30 10:38:33,527 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy01: start
2019-08-30 10:38:33,701 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy01: 111.231.90.122:8888  success
2019-08-30 10:38:33,702 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy01: error
2019-08-30 10:38:33,703 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:33,703 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy02: start
(101, '', '/tmp/execjs2kzdh357.js:2:0 Expected an operand but found <\n<!doctype html public "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd">\n^\n/tmp/execjs2kzdh357.js:3:0 Expected an operand but found <\n<html xmlns="http://www.w3.org/1999/xhtml">\n^\n/tmp/execjs2kzdh357.js:4:0 Expected an operand but found <\n<head>\n^\n/tmp/execjs2kzdh357.js:5:0 Expected an operand but found <\n<title>Ãâ·Ñ´úÀíip_·þÎñÆ÷http´úÀí_×îÐÂip´úÀí_Ãâ·ÑipÌáÈ¡ÍøÕ¾_¹úÄÚÍâ´úÀí_66Ãâ·Ñ´úÀíip</title><meta http-equiv="Content-Type" content="text/html; charset=gb2312" />\n^\n/tmp/execjs2kzdh357.js:6:0 Expected an operand but found <\n<meta name="keywords" content="ipÌáÈ¡£¬http´úÀí£¬¹úÄÚÍâ´úÀí£¬Ãâ·Ñ¸ßÄäÃû´úÀí£¬Ãâ·ÑipÌáÈ¡ÍøÕ¾£¬ip´úÀíÌáÈ                                                        ¡£¬Ãâ·Ñip´úÀí,´úÀíip,ip´úÀí,ip´úÀíÈí¼þ" />\n^\n/tmp/execjs2kzdh357.js:7:0 Expected an operand but found <\n<meta name="description" content="66Ãâ·Ñip´úÀíÍø£¨www.66ip.cn£©Ê±Ê±¸üÐÂ×îÐÂÃâ·Ñ´úÀíip¡¢http                                    ´úÀíÎªÖ÷,³£ÄêÌá¹©Ãâ·Ñ´úÀíip¡¢qq´úÀíip¡¢httpsÄäÃû´úÀí¡¢¹úÄÚ´úÀíÈí¼þµÈ¼ÓËÙ·þÎñ£¬ÎªÓÃ»§Ìá¹©×îÓÅÖÊ´úÀí."/>\n^\n/tmp/execjs2kzdh357.js:8:0 Expected an operand but found <\n<meta name=generator content="mshtml 8.00.7601.17514">\n^\n/tmp/execjs2kzdh357.js:9:0 Expected an operand but found <\n<script type="text/javascript" src="common/js/public.js">}\n^\n')
2019-08-30 10:38:34,491 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy03: start
2019-08-30 10:38:34,796 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy03: 1.197.10.62:9999     success
2019-08-30 10:38:34,797 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy03: error
2019-08-30 10:38:34,797 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:34,798 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy04: start
2019-08-30 10:38:34,926 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy04: 111.231.90.122:8888  success
2019-08-30 10:38:34,927 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy04: error
2019-08-30 10:38:34,927 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:34,928 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy05: start
2019-08-30 10:38:36,105 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy05: 114.234.82.192:9000  success
2019-08-30 10:38:36,106 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy05: error
2019-08-30 10:38:36,107 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:36,107 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy06: start
2019-08-30 10:38:37,000 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy06: 123.163.96.122:9999  success
2019-08-30 10:38:37,001 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy06: error
2019-08-30 10:38:37,001 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:37,002 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy07: start
2019-08-30 10:38:37,222 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy07: 180.103.0.214:808    success
2019-08-30 10:38:37,223 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy07: error
2019-08-30 10:38:37,224 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:37,224 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy08: start
2019-08-30 10:38:37,633 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy08: 223.99.214.21:53281  success
2019-08-30 10:38:37,634 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy08: error
2019-08-30 10:38:37,634 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:37,634 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy09: start
2019-08-30 10:38:37,727 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy09: 119.180.134.88:8060  success
2019-08-30 10:38:37,728 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy09: error
2019-08-30 10:38:37,728 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2019-08-30 10:38:37,729 ProxyScheduler.py[line:35] INFO finish fetch proxy
Traceback (most recent call last):
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 538, in connect
    sock = self._connect()
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 595, in _connect
    raise err
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 583, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "../Schedule/ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "../Schedule/ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "../Schedule/RawProxyCheck.py", line 65, in doRawProxyCheck
    for _proxy in pm.db.getAll():
  File "../DB/DbClient.py", line 102, in getAll
    return self.client.getAll()
  File "/home/zjy/software/git/proxy_pool/DB/SsdbClient.py", line 109, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/client.py", line 2717, in hgetall
    return self.execute_command('HGETALL', name)
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 1222, in get_connection
    connection.connect()
  File "/home/zjy/anaconda3/lib/python3.6/site-packages/redis/connection.py", line 543, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:8888. Connection refused.

`

**Comment by zhengdafangyuan** [comment]
搞明白了，没有运行Redis或者SSDB。安装和运行就好。
