### ISSUE TITLE
可以执行/get但不能执行/get_all

### ISSUE THREAD

**Issue by myktw** [jhao104/proxy_pool#355]
[2019-09-20 04:13:08,465] ERROR in app: Exception on /get_all/ [GET]
Traceback (most recent call last):
  File "F:\Program\proxy\lib\python\lib\site-packages\flask\app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "F:\Program\proxy\lib\python\lib\site-packages\flask\app.py", line 1952, in full_dispatch_request
    return self.finalize_request(rv)
  File "F:\Program\proxy\lib\python\lib\site-packages\flask\app.py", line 1967, in finalize_request
    response = self.make_response(rv)
  File "F:\Program\proxy\lib\python\lib\site-packages\flask\app.py", line 2130, in make_response
    " {rv.__class__.__name__}.".format(rv=rv)
TypeError: The view function did not return a valid response. The return type must be a string, dict, tuple, Response instance, or WSGI callable, but it was a list.
10.1.1.9 - - [20/Sep/2019 04:13:08] "GET /get_all/ HTTP/1.1" 500 -

**Comment by jhao104** [comment]
flask版本对吗
