### ISSUE TITLE
找不到hclear命令

### ISSUE THREAD

**Issue by Iris4-zmm** [jhao104/proxy_pool#384]
运行到finish fetch proxy，即将重新启动的位置开始报错，错误为：
redis.exceptions.ResponseError: unknown command 'hclear'
目前了解的是redis不包含ssdb中的hclear语句，单独配置了ssdb服务并打开，仍然会报错，请问应该怎么解决？

**Comment by jhao104** [comment]
数据库类型配置错误，redis就配REDIS

**Comment by Iris4-zmm** [comment]
不好意思，没有找到配置位置，请问应该在哪里配置？

**Comment by jhao104** [comment]
> 不好意思，没有找到配置位置，请问应该在哪里配置？

https://github.com/jhao104/proxy_pool/blob/5349289ff3e5679da7ceb62765ab4212ea40fdfe/Config/setting.py#L36

**Comment by Iris4-zmm** [comment]
更改该行为 DB_TYPE = getenv('db_type', 'redis').upper()
报错情况如下:
Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\Schedule\ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\Schedule\ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\Schedule\RawProxyCheck.py", line 67, in doRawProxyCheck
    pm.db.clear()
  File "..\DB\DbClient.py", line 105, in clear
    return self.client.clear()
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\proxy_pool-master\DB\SsdbClient.py", line 121, in clear
    return self.__conn.execute_command("hclear", self.name)
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\client.py", line 839, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\client.py", line 853, in parse_response
    response = connection.read_response()
  File "C:\Users\Iris\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\connection.py", line 718, in read_response
    raise response
redis.exceptions.ResponseError: unknown command 'hclear'

**Comment by jhao104** [comment]
REDIS

**Comment by Iris4-zmm** [comment]
谢谢你的耐心，我改了大小写，语句如下
DB_TYPE = getenv('db_type', 'REDIS').upper()
还是报错为redis.exceptions.ResponseError: unknown command 'hclear'
请问我是还有什么地方未更改吗？

**Comment by jhao104** [comment]
代码配置就这一处， 也可以通过设置环境变量`db_type`配置，docker方式启动可以通过`env`配置，
另外确认你代码是最新的

**Comment by Mr-Rongpj** [comment]
请问您现在解决这个问题了吗

**Comment by YumeMichi** [comment]
> 请问您现在解决这个问题了吗

确保你这几项都设置对了
https://github.com/jhao104/proxy_pool/blob/master/Config/setting.py#L36-L39

**Comment by Mr-Rongpj** [comment]
是的，完全一致，但还是没能解决这个问题，redis.exceptions.ResponseError: unknown command `hclear`, with args beginning with: `raw_proxy`,

**Comment by Mr-Rongpj** [comment]
> > 请问您现在解决这个问题了吗吗
> 
> 确保你这几项都设置对了
> https://github.com/jhao104/proxy_pool/blob/master/Config/setting.py#L36-L39
是的，完全一致，但还是没能解决这个问题，redis.exceptions.ResponseError：未知的命令hclear，与开始ARGS： raw_proxy，
