### ISSUE TITLE
Error 111 connecting to 127.0.0.1:8888. Connection refused.

### ISSUE THREAD

**Issue by qingsword** [jhao104/proxy_pool#412]
****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2020-01-11 12:27:22,433 ProxyScheduler.py[line:33] INFO start fetch proxy
2020-01-11 12:27:22,433 ProxyManager.py[line:44] INFO ProxyFetch : start
2020-01-11 12:27:22,434 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy01: start
2020-01-11 12:27:22,590 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy01: 183.146.213.157:80   success
2020-01-11 12:27:22,591 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy01: error
2020-01-11 12:27:22,591 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:22,592 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy02: start
Could not find an available JavaScript runtime.
2020-01-11 12:27:22,695 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy03: start
2020-01-11 12:27:23,018 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy03: 223.199.23.52:9999   success
2020-01-11 12:27:23,019 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy03: error
2020-01-11 12:27:23,020 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:23,020 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy04: start
2020-01-11 12:27:23,156 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy04: 183.146.213.157:80   success
2020-01-11 12:27:23,158 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy04: error
2020-01-11 12:27:23,158 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:23,158 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy05: start
2020-01-11 12:27:24,348 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy05: 144.52.197.19:9999   success
2020-01-11 12:27:24,352 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy05: error
2020-01-11 12:27:24,353 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:24,354 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy06: start
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854bd23410>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854bd391d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854bd39d90>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854ba8e050>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f854ba8e2d0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
2020-01-11 12:27:44,460 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy06: error
2020-01-11 12:27:44,461 ProxyManager.py[line:66] ERROR can only parse strings
2020-01-11 12:27:44,462 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy07: start
2020-01-11 12:27:44,631 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy07: 58.212.43.121:9999   success
2020-01-11 12:27:44,633 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy07: error
2020-01-11 12:27:44,633 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:44,634 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy08: start
2020-01-11 12:27:45,009 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy08: 123.163.122.247:9999 success
2020-01-11 12:27:45,011 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy08: error
2020-01-11 12:27:45,012 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:45,015 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy09: start
2020-01-11 12:27:45,419 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy09: 27.46.20.185:8888    success
2020-01-11 12:27:45,421 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy09: error
2020-01-11 12:27:45,421 ProxyManager.py[line:66] ERROR Error 111 connecting to 127.0.0.1:8888. Connection refused.
2020-01-11 12:27:45,422 ProxyScheduler.py[line:35] INFO finish fetch proxy
Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "../Schedule/ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "../Schedule/ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "../Schedule/RawProxyCheck.py", line 65, in doRawProxyCheck
    for _proxy in pm.db.getAll():
  File "../DB/DbClient.py", line 102, in getAll
    return self.client.getAll()
  File "/home/qing-v/proxy_pool/DB/SsdbClient.py", line 109, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 2717, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/local/lib/python2.7/dist-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 1224, in get_connection
    connection.connect()
  File "/usr/local/lib/python2.7/dist-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:8888. Connection refused.

按照大神的流程装上了依赖，Config里面的配置文件我没改，按照默认的，执行调度程序的时候报错了

**Comment by qingsword** [comment]
请问这个数据库是需要自己装上去吗？

**Comment by qingsword** [comment]
。。。解决了 自己装了个SSDB
