### ISSUE TITLE
Redis连接不上

### ISSUE THREAD

**Issue by LasyIsLazy** [jhao104/proxy_pool#417]
我用 Docker 拉的 Redis
![image](https://user-images.githubusercontent.com/18400251/73650659-a0dfb480-46bd-11ea-9ab7-471a0ffaf437.png)

密码确认无误（用 UI 工具已经可以成功连接到 Redis 了）

然后运行了以下命令：

```
docker run --env db_type=REDIS --env db_host=127.0.0.1 --env db_port=6379 --env db_password=redispw -p 5010:5010 jhao104/proxy_pool
```

错误如下：

```
2020-02-03 19:47:58,410 ProxyScheduler.py[line:35] INFO finish fetch proxy
Could not find an available JavaScript runtime.
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f209fc07da0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f209fc074a8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f209fc075f8>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f209fc07be0>: Failed to establish a new connection: [Errno -2] Name or service not known',))
HTTPSConnectionPool(host='proxy.coderbusy.com', port=443): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.VerifiedHTTPSConnection object at 0x7f209fc07b00>: Failed to establish a new connection: [Errno -2] Name or service not known',))
('Connection aborted.', RemoteDisconnected('Remote end closed connection without response',))
HTTPConnectionPool(host='ip.jiangxianli.com', port=80): Max retries exceeded with url: /?country=%E4%B8%AD%E5%9B%BD&?page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f209fb678d0>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='ip.jiangxianli.com', port=80): Max retries exceeded with url: /?country=%E4%B8%AD%E5%9B%BD&?page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f209fc07550>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='ip.jiangxianli.com', port=80): Max retries exceeded with url: /?country=%E4%B8%AD%E5%9B%BD&?page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f209fc07470>: Failed to establish a new connection: [Errno 111] Connection refused',))
HTTPConnectionPool(host='ip.jiangxianli.com', port=80): Max retries exceeded with url: /?country=%E4%B8%AD%E5%9B%BD&?page=1 (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f209fb67908>: Failed to establish a new connection: [Errno 111] Connection refused',))
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 539, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 596, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 584, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "../Schedule/ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "../Schedule/ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "../Schedule/RawProxyCheck.py", line 65, in doRawProxyCheck
    for _proxy in pm.db.getAll():
  File "../DB/DbClient.py", line 102, in getAll
    return self.client.getAll()
  File "/usr/src/app/DB/RedisClient.py", line 107, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2717, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1224, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 544, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.
```

**Comment by Victor2Code** [comment]
我也遇到了类似问题

**Comment by YumeMichi** [comment]
你在proxy_pool的容器里使用127.0.0.1的IP来连接另一个容器的redis肯定是连不上的 使用redis容器的IP或者docker网关的IP

**Comment by YumeMichi** [comment]
建议了解一下127.0.0.1是个什么地址

**Comment by Victor2Code** [comment]
@YumeMichi 两个容器连接到同一个bridge，然后连接到redis容器ip成功解决了问题，感谢你的提醒

**Comment by LasyIsLazy** [comment]
> 你在proxy_pool的容器里使用127.0.0.1的IP来连接另一个容器的redis肯定是连不上的 使用redis容器的IP或者docker网关的IP

将 127.0.0.1 替换成了容器的 IP 之后同样解决了问题，感谢

**Comment by masterzht** [comment]
项目不是有docker-compose吗，用docker-compose跑就好了，redis就不用单独运行了

**Comment by kuaile1993** [comment]
我页遇到了类似的问题，说我redis 密码没有设置，但是我的密码是设置了的，求解。。。。
****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2020-03-15 12:03:29,612 ProxyScheduler.py[line:33] INFO start fetch proxy
2020-03-15 12:03:29,612 ProxyManager.py[line:44] INFO ProxyFetch : start
2020-03-15 12:03:29,612 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy01: start
[2020-03-15 12:03:29 +0800] [8] [INFO] Starting gunicorn 19.9.0
[2020-03-15 12:03:29 +0800] [8] [INFO] Listening at: http://0.0.0.0:5010 (8)
[2020-03-15 12:03:29 +0800] [8] [INFO] Using worker: sync
[2020-03-15 12:03:29 +0800] [16] [INFO] Booting worker with pid: 16
[2020-03-15 12:03:29 +0800] [17] [INFO] Booting worker with pid: 17
[2020-03-15 12:03:29 +0800] [18] [INFO] Booting worker with pid: 18
2020-03-15 12:03:29,769 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy01: 115.29.199.16:8118   success
2020-03-15 12:03:29,772 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy01: error
2020-03-15 12:03:29,772 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:29,772 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy02: start
[2020-03-15 12:03:29 +0800] [19] [INFO] Booting worker with pid: 19
2020-03-15 12:03:29,877 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy03: start
2020-03-15 12:03:30,125 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy03: 123.132.232.254:37638 success
2020-03-15 12:03:30,127 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy03: error
2020-03-15 12:03:30,127 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:30,127 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy04: start
2020-03-15 12:03:30,251 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy04: 115.29.199.16:8318   success
2020-03-15 12:03:30,253 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy04: error
2020-03-15 12:03:30,253 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:30,253 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy05: start
2020-03-15 12:03:31,395 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy05: 125.110.75.250:9000  success
2020-03-15 12:03:31,397 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy05: error
2020-03-15 12:03:31,398 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:31,398 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy06: start
2020-03-15 12:03:31,562 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy07: start
2020-03-15 12:03:32,177 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy07: 58.218.25.5:9000     success
2020-03-15 12:03:32,179 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy07: error
2020-03-15 12:03:32,179 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:32,179 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy08: start
2020-03-15 12:03:33,286 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy08: 114.101.18.177:65309 success
2020-03-15 12:03:33,288 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy08: error
2020-03-15 12:03:33,288 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:33,289 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy09: start
2020-03-15 12:03:34,202 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy09: 112.109.198.106:3128 success
2020-03-15 12:03:34,204 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy09: error
2020-03-15 12:03:34,205 ProxyManager.py[line:66] ERROR Client sent AUTH, but no password is set
2020-03-15 12:03:34,205 ProxyScheduler.py[line:35] INFO finish fetch proxy
Could not find an available JavaScript runtime.
Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "../Schedule/ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "../Schedule/ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "../Schedule/RawProxyCheck.py", line 65, in doRawProxyCheck
    for _proxy in pm.db.getAll():
  File "../DB/DbClient.py", line 102, in getAll
    return self.client.getAll()
  File "/usr/src/app/DB/RedisClient.py", line 107, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 2717, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 836, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1224, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 548, in connect
    self.on_connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 618, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 700, in read_response
    response = self._parser.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 327, in read_response
    raise error
redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set


我的启动命令：docker run --name=proxy --env db_type=REDIS --env db_host=192.168.1.5 --env db_port=6379 --env db_password=123456 -p 5010:5010 jhao104/proxy_pool

**Comment by kuaile1993** [comment]
![image](https://user-images.githubusercontent.com/52553619/76695085-9d285000-66b5-11ea-85e6-a61cedba4dcd.png)
 客户端可连
