### ISSUE TITLE
用SSDB和REDIS都遇到这个问题

### ISSUE THREAD

**Issue by ztMin** [jhao104/proxy_pool#428]
****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2020-03-14 00:30:11,251 ProxyScheduler.py[line:33] INFO start fetch proxy
2020-03-14 00:30:11,251 ProxyManager.py[line:44] INFO ProxyFetch : start
2020-03-14 00:30:11,251 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy01: start
2020-03-14 00:30:11,410 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy01: 114.233.201.7:8118   success
2020-03-14 00:30:11,411 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy01: error
2020-03-14 00:30:11,412 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:11,412 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy02: start
(1, '', '[stdin]:2\n<!doctype html public "-//w3c//dtd xhtml 1.0 transitional//en" "http://www.w3.org/tr/xhtml1/dtd/xhtml1-transitional.dtd">\n^\n\nSyntaxError: Unexpected token <\n    at new Script (vm.js:80:7)\n    at createScript (vm.js:274:10)\n    at Object.runInThisContext (vm.js:326:10)\n    at Object.<anonymous> ([stdin]-wrapper:6:22)\n    at Module._compile (internal/modules/cjs/loader.js:701:30)\n    at evalScript (internal/bootstrap/node.js:589:27)\n    at Socket.<anonymous> (internal/bootstrap/node.js:323:15)\n    at Socket.emit (events.js:194:15)\n    at endReadableNT (_stream_readable.js:1125:12)\n    at process._tickCallback (internal/process/next_tick.js:63:19)\n')
2020-03-14 00:30:11,706 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy03: start
2020-03-14 00:30:11,869 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy03: 222.95.144.72:3000   success
2020-03-14 00:30:11,870 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy03: error
2020-03-14 00:30:11,871 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:11,871 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy04: start
2020-03-14 00:30:12,019 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy04: 114.233.201.7:8318   success
2020-03-14 00:30:12,020 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy04: error
2020-03-14 00:30:12,020 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:12,020 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy05: start
2020-03-14 00:30:13,086 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy05: 117.90.137.197:9000  success
2020-03-14 00:30:13,087 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy05: error
2020-03-14 00:30:13,087 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:13,087 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy06: start
2020-03-14 00:30:13,171 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy07: start
2020-03-14 00:30:13,453 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy07: 60.182.16.227:9000   success
2020-03-14 00:30:13,454 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy07: error
2020-03-14 00:30:13,454 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:13,454 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy08: start
2020-03-14 00:30:14,497 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy08: 114.101.18.177:65309 success
2020-03-14 00:30:14,498 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy08: error
2020-03-14 00:30:14,498 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:14,498 ProxyManager.py[line:46] INFO ProxyFetch - freeProxy09: start
2020-03-14 00:30:15,891 ProxyManager.py[line:61] INFO ProxyFetch - freeProxy09: 27.191.234.69:9999   success
2020-03-14 00:30:15,892 ProxyManager.py[line:65] ERROR ProxyFetch - freeProxy09: error
2020-03-14 00:30:15,892 ProxyManager.py[line:66] ERROR Connection closed by server.
2020-03-14 00:30:15,892 ProxyScheduler.py[line:35] INFO finish fetch proxy
Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "../Schedule/ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "../Schedule/ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "../Schedule/RawProxyCheck.py", line 65, in doRawProxyCheck
    for _proxy in pm.db.getAll():
  File "../DB/DbClient.py", line 102, in getAll
    return self.client.getAll()
  File "/root/www/proxy_pool/DB/RedisClient.py", line 107, in getAll
    item_dict = self.__conn.hgetall(self.name)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 2979, in hgetall
    return self.execute_command('HGETALL', name)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 734, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 316, in read_response
    response = self._buffer.readline()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 248, in readline
    self._read_from_socket()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 193, in _read_from_socket
    raise ConnectionError(SERVER_CLOSED_CONNECTION_ERROR)
redis.exceptions.ConnectionError: Connection closed by server.

**Comment by jhao104** [comment]
数据库配置错误
