### ISSUE TITLE
运行报错：redis.exceptions.ResponseError: unknown command 'hclear'

### ISSUE THREAD

**Issue by crazyZSShuo** [jhao104/proxy_pool#436]

**Comment by Bugbighuang** [comment]
me too,

**Comment by jhao104** [comment]
使用redis的话，`db_type` 配置为 `REDIS`

**Comment by Bugbighuang** [comment]
感谢，尝试后出现问题：存入了redis，但是网页不能随机get到一个，setting.py文件能否发我一份，我萌新在往爬虫进阶





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: J_hao104 <notifications@github.com&gt;
发送时间: 2020年4月7日 10:04
收件人: jhao104/proxy_pool <proxy_pool@noreply.github.com&gt;
抄送: Haha Huang <245624335@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jhao104/proxy_pool] 运行报错：redis.exceptions.ResponseError: unknown command 'hclear' (#436)

**Comment by jhao104** [comment]
> 感谢，尝试后出现问题：存入了redis，但是网页不能随机get到一个，setting.py文件能否发我一份，我萌新在往爬虫进阶 发自我的iPhone
> […](#)
> ------------------ 原始邮件 ------------------ 发件人: J_hao104 <notifications@github.com&gt; 发送时间: 2020年4月7日 10:04 收件人: jhao104/proxy_pool <proxy_pool@noreply.github.com&gt; 抄送: Haha Huang <245624335@qq.com&gt;, Comment <comment@noreply.github.com&gt; 主题: 回复：[jhao104/proxy_pool] 运行报错：redis.exceptions.ResponseError: unknown command 'hclear' (#436)

报错发出来

**Comment by harlay0728** [comment]
你好，我运行docker也报错，容器运行了一下会挂掉，报错如下：

2020-04-16 20:00:25,912 ProxyManager.py[line:57] INFO ProxyFetch - freeProxy14: 59.62.7.225:9000     exist
2020-04-16 20:00:25,912 ProxyManager.py[line:57] INFO ProxyFetch - freeProxy14: 60.162.64.21:9000    exist
2020-04-16 20:00:25,912 ProxyScheduler.py[line:35] INFO finish fetch proxy
Traceback (most recent call last):
  File "proxyPool.py", line 52, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 38, in schedule
    runScheduler()
  File "../Schedule/ProxyScheduler.py", line 48, in runScheduler
    rawProxyScheduler()
  File "../Schedule/ProxyScheduler.py", line 40, in rawProxyScheduler
    doRawProxyCheck()
  File "../Schedule/RawProxyCheck.py", line 67, in doRawProxyCheck
    pm.db.clear()
  File "../DB/DbClient.py", line 105, in clear
    return self.client.clear()
  File "/usr/src/app/DB/SsdbClient.py", line 120, in clear
    return self.__conn.execute_command("hclear", self.name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 878, in execute_command
    return self.parse_response(conn, command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 892, in parse_response
    response = connection.read_response()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 752, in read_response
    raise response
redis.exceptions.ResponseError: unknown command `hclear`, with args beginning with: `raw_proxy`, 

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

**Comment by Bugbighuang** [comment]
redis和ssdb别选错了





发自我的iPhone


------------------ 原始邮件 ------------------
发件人: harlay0728 <notifications@github.com&gt;
发送时间: 2020年4月16日 20:02
收件人: jhao104/proxy_pool <proxy_pool@noreply.github.com&gt;
抄送: Haha Huang <245624335@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jhao104/proxy_pool] 运行报错：redis.exceptions.ResponseError: unknown command 'hclear' (#436)

**Comment by harlay0728** [comment]
> 
> redis和ssdb别选错了 发自我的iPhone
> […](#)

多谢回复。我用的redis服务器，用docker-compose起的，配置如下，应该是没错的吧。我再看看吧
db_type: REDIS
db_host: 192.168.2.5
db_port: 6379

**Comment by Bugbighuang** [comment]
如果是docker要用映射端口号，谢谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: harlay0728 <notifications@github.com&gt;
发送时间: 2020年4月16日 21:19
收件人: jhao104/proxy_pool <proxy_pool@noreply.github.com&gt;
抄送: Haha Huang <245624335@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[jhao104/proxy_pool] 运行报错：redis.exceptions.ResponseError: unknown command 'hclear' (#436)





  
redis和ssdb别选错了 发自我的iPhone
 …
  
多谢回复。我用的redis服务器，用docker-compose起的，配置如下，应该是没错的吧。我再看看吧
 db_type: REDIS
 db_host: 192.168.2.5
 db_port: 6379

**Comment by harlay0728** [comment]
端口都是配好的，不过重新拉镜像，已经可以了

**Comment by harlay0728** [comment]
非常感谢
