### ISSUE TITLE
ImportError: cannot import name etree

### ISSUE THREAD

**Issue by y0unghe** [jhao104/proxy_pool#450]
Python 3.7.3 允许`./start.sh`后报错：

`from lxml import etree
ImportError: cannot import name etree
Traceback (most recent call last):
  File "proxyPool.py", line 21, in <module>
    from Config.setting import HEADER
  File "../Config/setting.py", line 94, in <module>
    checkConfig()
  File "../Config/setting.py", line 88, in checkConfig
    from ProxyGetter import getFreeProxy
  File "../ProxyGetter/getFreeProxy.py", line 21, in <module>
    from Util.WebRequest import WebRequest
  File "../Util/__init__.py", line 14, in <module>
    from Util.utilFunction import validUsefulProxy
  File "../Util/utilFunction.py", line 15, in <module>
    from lxml import etree
ImportError: cannot import name etree`

我检查了lxml路径，确实安装了的。

`
>>> import lxml
>>> lxml
<module 'lxml' from '/Library/Python/3.7/site-packages/lxml/__init__.py'>
`

`
> echo $PYTHONPATH
/Library/Python/3.7/site-packages
`

**Comment by jhao104** [comment]
@y0unghe 这我就不清楚了，试试重装大法
