### ISSUE TITLE
一直报这个错误，什么问题导致，是没抓取到代理？

### ISSUE THREAD

**Issue by cced3000** [jhao104/proxy_pool#465]
2020-06-19 11:39:45,408 UsefulProxyCheck.py[line:38] INFO UsefulProxyCheck - thread_6  : start
2020-06-19 11:39:45,408 UsefulProxyCheck.py[line:38] INFO UsefulProxyCheck - thread_7  : start
2020-06-19 11:39:45,409 UsefulProxyCheck.py[line:38] INFO UsefulProxyCheck - thread_8  : start
Exception in thread thread_7:
Traceback (most recent call last):
  File "/www/server/panel/pyenv/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "../Schedule/UsefulProxyCheck.py", line 48, in run
    proxy_obj, status = checkProxyUseful(proxy_obj)
  File "../ProxyHelper/ProxyUtil.py", line 27, in checkProxyUseful
    if validUsefulProxy(proxy_obj.proxy):
AttributeError: 'NoneType' object has no attribute 'proxy'

**Comment by jhao104** [comment]
跑过历史版本的话需要手动清空下数据库，然后代码拉发布的文档分支，慎用master分支
