### ISSUE TITLE
centos 6下，Python2.7.1 运行报错

### ISSUE THREAD

**Issue by whx4J8** [jhao104/proxy_pool#48]
`

[root@VPS Run]# python main.py 
Traceback (most recent call last):
  File "main.py", line 22, in <module>
    from Schedule.ProxyRefreshSchedule import run as RefreshRun
  File "../Schedule/ProxyRefreshSchedule.py", line 21, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "/usr/local/python27/lib/python2.7/site-packages/apscheduler/__init__.py", line 2, in <module>
    release = __import__('pkg_resources').get_distribution('APScheduler').version.split('-')[0]
  File "/usr/local/python27/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 292, in get_distribution
    if isinstance(dist,Requirement): dist = get_provider(dist)
  File "/usr/local/python27/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 176, in get_provider
    return working_set.find(moduleOrReq) or require(str(moduleOrReq))[0]
  File "/usr/local/python27/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 648, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/usr/local/python27/lib/python2.7/site-packages/distribute-0.6.10-py2.7.egg/pkg_resources.py", line 546, in resolve
    raise DistributionNotFound(req)
pkg_resources.DistributionNotFound: APScheduler`

**Comment by whx4J8** [comment]
麻烦帮忙看下，是我的版本问题吗。谢谢：）

**Comment by jhao104** [comment]
centos下面python是2.6的吧
用2.7

**Comment by cyjaysun** [comment]
我用的就是centos下python2.7 ,遇到了同样的报错.

**Comment by jhao104** [comment]
@cyjaysun 检查下APScheduler的版本吧
参考：https://github.com/jhao104/proxy_pool/issues/101

**Comment by cyjaysun** [comment]
@jhao104  已解决。手动更改site-packages/apscheduler/\_\_init\_\_.py至对应版本就好了。thks.
