### ISSUE TITLE
执行后报错信息Client sent AUTH, but no password is set    

### ISSUE THREAD

**Issue by fxlysm** [jhao104/proxy_pool#486]
2020-07-14 19:34:07,356 check.py[line:87] INFO ProxyCheck - thread_19  : 49.86.59.75:9999        fail          Exception in thread thread_04:                                                                                 Traceback (most recent call last):                                                                               File "C:\Python\Python36\lib\threading.py", line 916, in _bootstrap_inner                                        self.run()                                                                                                   File "D:\dev\Pycharm\github\proxy_pool\helper\check.py", line 81, in run                                         if self.proxy_handler.exists(proxy):                                                                         File "D:\dev\Pycharm\github\proxy_pool\handler\proxyHandler.py", line 77, in exists                              return self.db.exists(proxy.proxy)                                                                           File "D:\dev\Pycharm\github\proxy_pool\db\dbClient.py", line 107, in exists                                      return self.client.exists(key, **kwargs)                                                                     File "D:\dev\Pycharm\github\proxy_pool\db\redisClient.py", line 91, in exists                                    return self.__conn.hexists(self.name, proxy_str)                                                             File "C:\Python\Python36\lib\site-packages\redis\client.py", line 1820, in hexists                               return self.execute_command('HEXISTS', name, key)                                                            File "C:\Python\Python36\lib\site-packages\redis\client.py", line 564, in execute_command                        connection.send_command(*args)                                                                               File "C:\Python\Python36\lib\site-packages\redis\connection.py", line 556, in send_command                       self.send_packed_command(self.pack_command(*args))                                                           File "C:\Python\Python36\lib\site-packages\redis\connection.py", line 532, in send_packed_command                self.connect()                                                                                               File "C:\Python\Python36\lib\site-packages\redis\connection.py", line 440, in connect                            self.on_connect()                                                                                            File "C:\Python\Python36\lib\site-packages\redis\connection.py", line 508, in on_connect                         if nativestr(self.read_response()) != 'OK':                                                                  File "C:\Python\Python36\lib\site-packages\redis\connection.py", line 574, in read_response                      raise response                                                                                             redis.exceptions.ResponseError: Client sent AUTH, but no password is set                                                                                                                                                      Exception in thread thread_18:
--

**Comment by 2440012586** [comment]
我也是这个问题，该怎么解决啊
