### ISSUE TITLE
你好，请问一下，redis.exceptions.ResponseError: invalid DB index怎么解决？

### ISSUE THREAD

**Issue by xiaobaidebai** [jhao104/proxy_pool#498]
docker起来后发现报错，上网找了好多的方法都不行
Exception in thread thread_10:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/helper/check.py", line 81, in run
    if self.proxy_handler.exists(proxy):
  File "/app/handler/proxyHandler.py", line 77, in exists
    return self.db.exists(proxy.proxy)
  File "/app/db/dbClient.py", line 107, in exists
    return self.client.exists(key, **kwargs)
  File "/app/db/redisClient.py", line 91, in exists
    return self.__conn.hexists(self.name, proxy_str)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3006, in hexists
    return self.execute_command('HEXISTS', name, key)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1379, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 664, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: invalid DB index
另外想问一下，这个问题会影响网页的请求吗？
直接访问：5010是可以正常访问的
http://127.0.0.1:5010/
delete?proxy=127.0.0.1:8080	"delete an unable proxy"
get	"get an useful proxy"
get_all	"get all proxy from proxy pool"
get_status	"proxy number"
pop	"get and delete an useful proxy"
但访问/get的话报错

Internal Server Error

The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jhao104** [comment]
这是你`redis://:password@ip:port/db`配置的db有问题，db是0到15的一个数字

**Comment by xiaobaidebai** [comment]
我明白了，谢谢老哥，没怎么接触过redis，看来得补补课才行了
