### ISSUE TITLE
centos7访问报错

### ISSUE THREAD

**Issue by colddew** [jhao104/proxy_pool#50]
```
ERROR in app: Exception on /get/ [GET]
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python/lib/python2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/python/lib/python2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
ERROR:Api.ProxyApi:Exception on /get/ [GET]
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/flask/app.py", line 1988, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/python/lib/python2.7/site-packages/flask/app.py", line 1642, in full_dispatch_request
    response = self.make_response(rv)
  File "/usr/local/python/lib/python2.7/site-packages/flask/app.py", line 1731, in make_response
    raise ValueError('View function did not return a response')
ValueError: View function did not return a response
```

centos7 python2.7.13，使用 `curl http://localhost:5000/get/` 本地测试没问题，国外的云服务器上访问就报错

另外定时任务可能也有问题，python不是很熟能帮忙看下都是什么问题，怎么解决呢

```
ERROR:apscheduler.executors.default:Job "main (trigger: interval[0:05:00], next run at: 2017-07-07 17:29:56 CST)" raised an exception
Traceback (most recent call last):
  File "/usr/local/python/lib/python2.7/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 73, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 42, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "../ProxyGetter/getFreeProxy.py", line 80, in freeProxySecond
    for proxy in re.findall(r'\d{1,3}\.\d{1,3}\.\d{1,3}\.\d{1,3}:\d{1,5}', html):
  File "/usr/local/python/Lib/re.py", line 181, in findall
    return _compile(pattern, flags).findall(string)
TypeError: expected string or buffer
```

**Comment by colddew** [comment]
删掉了几个代理源等了一段时间现在可以get到数据了，但没有可用代理时访问api一直抛异常感觉这个不是很友好

**Comment by jhao104** [comment]
确实，有两个地方没有处理，
一是:代理抓取的方法出错会影响;
二是:代理池为空了会影响;
加个判断就行，会面有时间加上

**Comment by colddew** [comment]
今天又在腾讯云找了台位于上海的机器部署了下，结果可用的依然很少只有25个可用的。而本地也起了应用居然有373个可用的，我所在的城市和上海很近，差了一个数量还有可能什么原因导致的呢
