### ISSUE TITLE
start server error

### ISSUE THREAD

**Issue by SongyuanHan** [jhao104/proxy_pool#507]
Traceback (most recent call last):
  File "proxyPool.py", line 45, in <module>
    cli()
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 40, in server
    from api.proxyApi import runFlask
  File "/root/src/proxy_pool/proxy_pool/api/proxyApi.py", line 28, in <module>
    app = Flask('api.proxyApi')
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 556, in __init__
    self.add_url_rule(
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 64, in wrapper_func
    return f(self, *args, **kwargs)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/flask/app.py", line 1214, in add_url_rule
    self.url_map.add(rule)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/werkzeug/routing.py", line 1386, in add
    rule.bind(self)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/werkzeug/routing.py", line 730, in bind
    self.compile()
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/werkzeug/routing.py", line 794, in compile
    self._build = self._compile_builder(False).__get__(self, None)
  File "/root/.pyenv/versions/3.8.1/lib/python3.8/site-packages/werkzeug/routing.py", line 945, in _compile_builder
    code = compile(module, "<werkzeug routing>", "exec")
TypeError: required field "type_ignores" missing from Module

fix:
Upgrade  werkzeug to 0.15.5

**Comment by DrAlexsoon** [comment]
可能是因为python版本和werkzeug不兼容的原因
python@3.8 中werkzeug routing.py#944中 需要修改为
```python
 module = ast.fix_missing_locations(ast.Module([func_ast],[])) 
```

**Comment by 1151806933** [comment]
能具体解释一下么

**Comment by jhao104** [comment]
@1151806933 https://github.com/jhao104/proxy_pool/issues/565#issuecomment-834143232
