### ISSUE TITLE
启动服务时报错

### ISSUE THREAD

**Issue by ZainCheung** [jhao104/proxy_pool#521]
报错信息如下：
Traceback (most recent call last):
  File "proxyPool.py", line 47, in <module>
    cli()
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/lib64/python2.7/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 42, in server
    from api.proxyApi import runFlask
  File "/www/wwwroot/proxy_pool/api/proxyApi.py", line 20, in <module>
    from flask import Flask, jsonify, request
  File "/usr/lib/python2.7/site-packages/flask/__init__.py", line 21, in <module>
    from .app import Flask, Request, Response
  File "/usr/lib/python2.7/site-packages/flask/app.py", line 23, in <module>
    from werkzeug.routing import BuildError, Map, RequestRedirect, Rule
  File "/usr/lib64/python2.7/site-packages/werkzeug/routing.py", line 948
    exec(code, globs, locs)
SyntaxError: unqualified exec is not allowed in function '_compile_builder' it contains a nested function with free variables

**Comment by jhao104** [comment]
确认依赖版本和要求一致
