### ISSUE TITLE
调用API出现如下问题

### ISSUE THREAD

**Issue by dameassz** [jhao104/proxy_pool#523]
Internal Server Error
The server encountered an internal error and was unable to complete your request. Either the server is overloaded or there is an error in the application.

**Comment by jhao104** [comment]
贴server的错误日志

**Comment by ChrisLiang2020** [comment]
![image](https://user-images.githubusercontent.com/73007745/102190191-a9666580-3ef2-11eb-9923-4b7f63fb7528.png)

**Comment by ChrisLiang2020** [comment]
我也遇到了这个错误，请教一下
 * Running on http://127.0.0.1:5010/ (Press CTRL+C to quit)
[2020-12-15 16:26:39,160] ERROR in app: Exception on /get/ [GET]
Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "D:\Python36\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "D:\Python36\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python36\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Python36\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Python36\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Python36\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Python36\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Python36\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Administrator\Desktop\proxy_pool-2.1.0\api\proxyApi.py", line 60, in get
    proxy = proxy_handler.get()
  File "C:\Users\Administrator\Desktop\proxy_pool-2.1.0\handler\proxyHandler.py", line 33, in get
    proxy = self.db.get()
  File "C:\Users\Administrator\Desktop\proxy_pool-2.1.0\db\dbClient.py", line 95, in get
    return self.client.get(**kwargs)
  File "C:\Users\Administrator\Desktop\proxy_pool-2.1.0\db\redisClient.py", line 48, in get
    proxies = self.__conn.hkeys(self.name)
  File "D:\Python36\lib\site-packages\redis\client.py", line 3028, in hkeys
    return self.execute_command('HKEYS', name)
  File "D:\Python36\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\Python36\lib\site-packages\redis\connection.py", line 1379, in get_connection
    connection.connect()
  File "D:\Python36\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.
127.0.0.1 - - [15/Dec/2020 16:26:40] "[1m[35mGET /get/ HTTP/1.1[0m" 500 -
127.0.0.1 - - [15/Dec/2020 16:26:40] "[33mGET /favicon.ico HTTP/1.1[0m" 404 -

**Comment by ChrisLiang2020** [comment]
人傻了，没启动Redis，没事了
