### ISSUE TITLE
Interval Server Error

### ISSUE THREAD

**Issue by RobertLou** [jhao104/proxy_pool#526]
[2020-12-17 00:34:27,202] ERROR in app: Exception on /get/ [GET]
Traceback (most recent call last):
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Coding\Python\爬\proxy_pool\api\proxyApi.py", line 60, in get
    proxy = proxy_handler.get()
  File "D:\Coding\Python\爬\proxy_pool\handler\proxyHandler.py", line 33, in get
    proxy = self.db.get()
  File "D:\Coding\Python\爬\proxy_pool\db\dbClient.py", line 103, in get
    return self.client.get(**kwargs)
  File "D:\Coding\Python\爬\proxy_pool\db\redisClient.py", line 48, in get
    proxies = self.__conn.hkeys(self.name)
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\client.py", line 3028, in hkeys
    return self.execute_command('HKEYS', name)
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\connection.py", line 1379, in get_connection
    connection.connect()
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\connection.py", line 567, in connect
    self.on_connect()
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "C:\Users\28743\AppData\Local\Programs\Python\Python37-32\lib\site-packages\redis\connection.py", line 340, in read_response
    raise error
redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set
127.0.0.1 - - [17/Dec/2020 00:34:27] "GET /get/ HTTP/1.1" 500 -
在调用get方法时产生的问题
还有现在版本需要运行redis吗？我运不运行结果都一样（redis维持在那个可以PING PONG的界面）

**Comment by jhao104** [comment]
`redis.exceptions.AuthenticationError: Client sent AUTH, but no password is set`
redis密码没有配

**Comment by cheshennull** [comment]
您好，我也遇到了这个报错，运行api后，可以正常执行，但是过一两分钟就500错误了，redis密码已经配置了

**Comment by cheshennull** [comment]
![Uploading 1.png…]()

**Comment by cheshennull** [comment]
![1](https://user-images.githubusercontent.com/42889666/146666879-4970b502-be9d-44fb-bc42-404e70358378.png)
