### ISSUE TITLE
访问接口报错,redis里有数据

### ISSUE THREAD

**Issue by rynarzzz** [jhao104/proxy_pool#542]
127.0.0.1 - - [25/Feb/2021 17:45:26] "GET /get/ HTTP/1.1" 500 -
[2021-02-25 17:45:27,952] ERROR in app: Exception on /get/ [GET]
Traceback (most recent call last):
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\connection.py", line 559, in connect
    sock = self._connect()
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\connection.py", line 615, in _connect
    raise err
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\connection.py", line 603, in _connect
    sock.connect(socket_address)
OSError: [WinError 10049] ▒▒▒▒▒▒▒▒▒▒▒У▒▒▒▒▒▒▒ĵ▒ַ▒▒Ч▒▒

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\flask\app.py", line 2284, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\flask\app.py", line 1807, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\flask\app.py", line 1710, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\flask\_compat.py", line 35, in reraise
    raise value
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\flask\app.py", line 1805, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\flask\app.py", line 1791, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Workspace\proxy_pool-2.1.1\api\proxyApi.py", line 60, in get
    proxy = proxy_handler.get()
  File "D:\Workspace\proxy_pool-2.1.1\handler\proxyHandler.py", line 33, in get
    proxy = self.db.get()
  File "D:\Workspace\proxy_pool-2.1.1\db\dbClient.py", line 103, in get
    return self.client.get(**kwargs)
  File "D:\Workspace\proxy_pool-2.1.1\db\redisClient.py", line 48, in get
    proxies = self.__conn.hkeys(self.name)
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\client.py", line 3028, in hkeys
    return self.execute_command('HKEYS', name)
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\connection.py", line 1379, in get_connection
    connection.connect()
  File "D:\Workspace\proxy_pool-2.1.1\venv\lib\site-packages\redis\connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10049 connecting to 127.0.0.1:6379. ▒▒▒▒▒▒▒▒▒▒▒У▒▒▒▒▒▒▒ĵ▒ַ▒▒Ч▒▒.

**Comment by jhao104** [comment]
Error 10049 connecting to 127.0.0.1:6379.  redis连不上
