### ISSUE TITLE
docker容器不能正常运行

### ISSUE THREAD

**Issue by shuaidie** [jhao104/proxy_pool#543]
****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

VERSION: 2.1.1

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

VERSION: 2.1.1

Traceback (most recent call last):
  File "proxyPool.py", line 47, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 42, in server
    from api.proxyApi import runFlask
  File "/app/api/proxyApi.py", line 29, in <module>
    proxy_handler = ProxyHandler()
  File "/app/handler/proxyHandler.py", line 25, in __init__
    self.db = DbClient(self.conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 57, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 66, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'
Traceback (most recent call last):
  File "proxyPool.py", line 47, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 34, in schedule
    runScheduler()
  File "/app/helper/scheduler.py", line 49, in runScheduler
    _runProxyFetch()
  File "/app/helper/scheduler.py", line 31, in _runProxyFetch
    for proxy in runFetcher():
  File "/app/helper/fetch.py", line 63, in runFetcher
    return Fetcher().fetch()
  File "/app/helper/fetch.py", line 27, in __init__
    self.proxy_handler = ProxyHandler()
  File "/app/handler/proxyHandler.py", line 25, in __init__
    self.db = DbClient(self.conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 57, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 66, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 169, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'

**Comment by jhao104** [comment]
看最后一行，配置有问题 port配置不对

**Comment by shuaidie** [comment]
> 看最后一行，配置有问题 port配置不对
哈哈，的确是redis没有配置好，现在可以运行了，没仔细看命令，我还以为docker里面已经有配置好redis。

**Comment by TophTab** [comment]
意思是redis需要自己安装吗？

**Comment by shuaidie** [comment]
> 意思是redis需要自己安装吗？

是的，装个redis，然后端口设置好就行
