### ISSUE TITLE
redis 报错 ，是否是我的redis 版本太高了

### ISSUE THREAD

**Issue by phcbest** [jhao104/proxy_pool#544]
Exception in thread thread_01:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/threading.py", line 916, in _bootstrap_inner
    self.run()
  File "/app/helper/check.py", line 81, in run
    if self.proxy_handler.exists(proxy):
  File "/app/handler/proxyHandler.py", line 77, in exists
    return self.db.exists(proxy.proxy)
  File "/app/db/dbClient.py", line 115, in exists
    return self.client.exists(key, **kwargs)
  File "/app/db/redisClient.py", line 91, in exists
    return self.__conn.hexists(self.name, proxy_str)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3006, in hexists
    return self.execute_command('HEXISTS', name, key)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1379, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 664, in on_connect
    if nativestr(self.read_response()) != 'OK':
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: value is not an integer or out of range

**Comment by csh0101** [comment]
请问这个问题后来发现是什么

**Comment by csh0101** [comment]
我知道了 是我。。。有问题

**Comment by phcbest** [comment]
long time i not remember
