### ISSUE TITLE
redis 没有设置密码 用bridge连接 redis服务器开着的 

### ISSUE THREAD

**Issue by kak1fang** [jhao104/proxy_pool#549]
ob "proxy检查 (trigger: interval[0:02:00], next run at: 2021-03-23 11:27:26 CST)" raised an exception
Traceback (most recent call last):
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/apscheduler/executors/base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/helper/scheduler.py", line 40, in _runProxyCheck
    if proxy_handler.db.getCount() < proxy_handler.conf.poolSizeMin:
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/db/dbClient.py", line 130, in getCount
    return self.client.getCount()
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/db/redisClient.py", line 121, in getCount
    return self.__conn.hlen(self.name)
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/redis/client.py", line 3032, in hlen
    return self.execute_command('HLEN', name)
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/redis/connection.py", line 1379, in get_connection
    connection.connect()
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/Users/kakifang/Documents/random_python/proxy_pool-master/venv/lib/python3.9/site-packages/redis/connection.py", line 756, in read_response
    raise response
redis.exceptions.ResponseError: AUTH <password> called without any password configured for the default user. Are you sure your configuration is correct?
2021-03-23 11:25:31,881 webRequest.py[line:80] ERROR requests: http://www.xiladaili.com/https/ error: HTTPConnectionPool(host='127.0.0.1', port=50724): R

**Comment by jhao104** [comment]
没有密码的话确认配置 DB_CONN = 'redis://:@IP:port/0'
