### ISSUE TITLE
启动webApi服务报错，求教o(╥﹏╥)o

### ISSUE THREAD

**Issue by liukk18** [jhao104/proxy_pool#583]
当我运行 python proxyPool.py server 报错如下：
![image](https://user-images.githubusercontent.com/56376032/124201954-f0711c80-db0b-11eb-85c4-03f4d106d1c7.png)
不知如何解决  求求大神指点

**Comment by jhao104** [comment]
是不是端口被占用，重复启动了

**Comment by liukk18** [comment]
我刚刚查看了端口使用情况：  好像没有被占用
![image](https://user-images.githubusercontent.com/56376032/124207826-e99cd680-db18-11eb-9cfb-3a16afee3be0.png)

**Comment by jhao104** [comment]
x86_64-conda_ 这个是你配置的ip么

**Comment by jhao104** [comment]
或者你换成127.0.0.1试试

**Comment by liukk18** [comment]
setting.py 里的配置吗  我是这样设置的：
![image](https://user-images.githubusercontent.com/56376032/124209395-0b4b8d00-db1c-11eb-8523-0f941474ab82.png)

**Comment by liukk18** [comment]
python proxyPool.py schedule  可以正常运行  并且redis数据库中也有ip存入  但是访问不了http://127.0.0.1:5010/get/  
只访问http://127.0.0.1  会出现：
![image](https://user-images.githubusercontent.com/56376032/124210797-a2b1df80-db1e-11eb-9d8f-580fb1fd51ec.png)

**Comment by jhao104** [comment]
80端口是你自己另外的服务

**Comment by liukk18** [comment]
嗷嗷  那还有可能是哪里出了问题。
我用docker运行也报错：
![image](https://user-images.githubusercontent.com/56376032/124211750-3df78480-db20-11eb-80e4-a4c4b1629c8c.png)

**Comment by jhao104** [comment]
> 嗷嗷 那还有可能是哪里出了问题。
> 我用docker运行也报错：
> ![image](https://user-images.githubusercontent.com/56376032/124211750-3df78480-db20-11eb-80e4-a4c4b1629c8c.png)

你这是网的问题 拉不下来镜像

**Comment by jhao104** [comment]
你可以试试把
https://github.com/jhao104/proxy_pool/blob/78b05ae50d8208890e85683ec5cbcc5e83cb9def/api/proxyApi.py#L99
这句改成
```
 if 1: 
```
直接以Flask运行看看

**Comment by liukk18** [comment]
改完之后运行python proxyApi.py  报错了：
* Serving Flask app "proxyApi" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployme              nt.
   Use a production WSGI server instead.
 * Debug mode: off
Traceback (most recent call last):
  File "proxyApi.py", line 140, in <module>
    runFlask()
  File "proxyApi.py", line 109, in runFlask
    app.run(host=conf.serverHost, port=conf.serverPort)
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/site-packages/flask/app.py",               line 990, in run
    run_simple(host, port, self, **options)
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/site-packages/werkzeug/servi              ng.py", line 1009, in run_simple
    inner()
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/site-packages/werkzeug/servi              ng.py", line 962, in inner
    fd=fd,
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/site-packages/werkzeug/servi              ng.py", line 805, in make_server
    host, port, app, request_handler, passthrough_errors, ssl_context, fd=fd
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/site-packages/werkzeug/servi              ng.py", line 698, in __init__
    HTTPServer.__init__(self, server_address, handler)
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/socketserver.py", line 452,               in __init__
    self.server_bind()
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/http/server.py", line 137, i              n server_bind
    socketserver.TCPServer.server_bind(self)
  File "/home/liuk/anaconda3/envs/py3/lib/python3.7/socketserver.py", line 466,               in server_bind
    self.socket.bind(self.server_address)
socket.gaierror: [Errno -2] Name or service not known

查找原因是说host名称没有在配置文件中指定，因此无法找到对应的IP，需要修改hosts文件，可是我看我的host 文件好像已经指定了ip诶
![image](https://user-images.githubusercontent.com/56376032/124213571-69c83980-db23-11eb-92a4-1fd9cba5a892.png)

**Comment by jhao104** [comment]
这个报错就是你机器识别不了配置IP

**Comment by liukk18** [comment]
那我如果把网的问题解决了，换docker运行能成功不

**Comment by jhao104** [comment]
> 那我如果把网的问题解决了，换docker运行能成功不

项目本身就是可以运行的，包括直接跑代码和docker

**Comment by liukk18** [comment]
好的 我再试试 感谢大佬回答，谢谢！
