### ISSUE TITLE
docker-compose可以运行，但是本地机子上使用api出错

### ISSUE THREAD

**Issue by RobinlinGit** [jhao104/proxy_pool#594]
我将服务端口统一改成了14444，包括dockerfile里的expose，setting里的改动如下：
```
HOST = "127.0.0.1"

PORT = 14444

# ############### database config ###################
# db connection uri
# example:
#      Redis: redis://:password@ip:port/db
#      Ssdb:  ssdb://:password@ip:port
DB_CONN = 'redis://127.0.0.1:6379/0'
```

docker-compose.yml如下：
```
version: '2'
services:
  proxy_pool:
    build: .
    container_name: proxy_pool
    ports:
      - "14444:14444"
    links:
      - proxy_redis
    environment:
      DB_CONN: "redis://@proxy_redis:6379/0"
  proxy_redis:
    image: "redis"
    container_name: proxy_redis
```
然后在该项目下运行命令```docker-compose up```，程序正常运行，但是调用api```requests.get("http://127.0.0.1:14444/get/")```时出现如下错误：
```
Traceback (most recent call last):
  File "d:\Project\proxy_pool\test_proxy.py", line 31, in <module>
    print(get_proxy())
  File "d:\Project\proxy_pool\test_proxy.py", line 7, in get_proxy
    return requests.get(f"http://127.0.0.1:{port}/get/").json()
  File "C:\Users\robin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\api.py", line 61, in request
    return session.request(method=method, url=url, **kwargs)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 542, in request
    resp = self.send(prep, **send_kwargs)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\sessions.py", line 655, in send
    r = adapter.send(request, **kwargs)
  File "C:\Users\robin\AppData\Local\Programs\Python\Python39\lib\site-packages\requests\adapters.py", line 498, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', RemoteDisconnected('Remote end closed connection without response'))
```
想问一下是不是哪里配置错了

**Comment by reoLantern** [comment]
@lzh23333 您好，想问一下这个问题是怎么解决的，我也遇到了相同的问题，谢谢！
