### ISSUE TITLE
大神请帮忙看看

### ISSUE THREAD

**Issue by kisller** [jhao104/proxy_pool#597]
2021-09-25 22:42:08,810 launcher.py[line:61] INFO DB_HOST: 127.0.0.1
2021-09-25 22:42:08,810 launcher.py[line:62] INFO DB_PORT: 6379
2021-09-25 22:42:08,810 launcher.py[line:62] INFO DB_PORT: 6379
2021-09-25 22:42:08,810 launcher.py[line:63] INFO DB_NAME: 0
2021-09-25 22:42:08,810 launcher.py[line:63] INFO DB_NAME: 0
2021-09-25 22:42:08,810 launcher.py[line:64] INFO DB_USER: 
2021-09-25 22:42:08,810 launcher.py[line:64] INFO DB_USER: 
2021-09-25 22:42:08,810 launcher.py[line:65] INFO =================================================
2021-09-25 22:42:08,810 launcher.py[line:65] INFO =================================================
2021-09-25 22:42:08,813 redisClient.py[line:149] ERROR redis connection error: Error 111 connecting to 127.0.0.1:6379. Connection refused.
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 559, in connect
    sock = self._connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 615, in _connect
    raise err
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 603, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/db/redisClient.py", line 144, in test
    self.getCount()
  File "/app/db/redisClient.py", line 130, in getCount
    proxies = self.getAll(https=False)
  File "/app/db/redisClient.py", line 112, in getAll
    items = self.__conn.hvals(self.name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 3084, in hvals
    return self.execute_command('HVALS', name)
  File "/usr/local/lib/python3.6/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 1379, in get_connection
    connection.connect()
  File "/usr/local/lib/python3.6/site-packages/redis/connection.py", line 563, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 111 connecting to 127.0.0.1:6379. Connection refused.

**Comment by jhao104** [comment]
日志很清楚 数据库`127.0.0.1:6379`连不上 检查你的配置和环境

**Comment by sfz009900** [comment]
直接git clone下来后到目录运行docker-compose -f docker-compose.yml up -d

**Comment by LiuWenJia-ops** [comment]
就是说, 得把 redis 先启动起来...
