### ISSUE TITLE
ssdb兼容问题

### ISSUE THREAD

**Issue by vc5** [jhao104/proxy_pool#60]
python3环境下安装ssdb报错,3.4.3和3.6.2环境下均无法安装，建议采用[pyssdb](https://pypi.python.org/pypi/pyssdb)或者[ssdb.py](https://pypi.python.org/pypi/ssdb.py)
```bash
ubuntu@hp:~/workspace/proxy_pool/Run$ python -V
Python 3.6.2
ubuntu@hp:~/workspace/proxy_pool/Run$ pip install ssdb
Collecting ssdb
  Using cached ssdb-0.0.3.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-srsinocq/ssdb/setup.py", line 5, in <module>
        from ssdb import __version__
      File "/tmp/pip-build-srsinocq/ssdb/ssdb/__init__.py", line 2, in <module>
        from ssdb.client import StrictSSDB, SSDB
      File "/tmp/pip-build-srsinocq/ssdb/ssdb/client.py", line 3, in <module>
        from itertools import chain, starmap, izip_longest
    ImportError: cannot import name 'izip_longest'
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-srsinocq/ssdb/
```

**Comment by jhao104** [comment]
解决方法先参考下这个：http://blog.csdn.net/a1368783069/article/details/51398625

ssdb这个东西要换，维护的人都下岗了。。
