### ISSUE TITLE
AuthenticationError: Client sent AUTH, but no password is set

### ISSUE THREAD

**Issue by 2440012586** [jhao104/proxy_pool#625]
[root@iZm5edcqv0ak6r3z1ayc8vZ proxy_pool-master]# python proxyPool.py schedule

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2022-01-11 15:41:15,913 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-01-11 15:41:15,914 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-01-11 15:41:15,914 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-01-11 15:41:15,914 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-01-11 15:41:15,957 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-01-11 15:41:15,957 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-01-11 15:41:15,957 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2022-01-11 15:41:15,957 launcher.py[line:61] INFO DB_PORT: 6379
2022-01-11 15:41:15,957 launcher.py[line:62] INFO DB_NAME: 0
2022-01-11 15:41:15,957 launcher.py[line:63] INFO DB_USER:
2022-01-11 15:41:15,957 launcher.py[line:64] INFO =================================================
2022-01-11 15:41:15,959 redisClient.py[line:149] ERROR redis connection error: Client sent AUTH, but no password is set
Traceback (most recent call last):
  File "/opt/proxy_pool-master/db/redisClient.py", line 144, in test
    self.getCount()
  File "/opt/proxy_pool-master/db/redisClient.py", line 130, in getCount
    proxies = self.getAll(https=False)
  File "/opt/proxy_pool-master/db/redisClient.py", line 112, in getAll
    items = self.__conn.hvals(self.name)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 3084, in hvals
    return self.execute_command('HVALS', name)
  File "/usr/lib/python2.7/site-packages/redis/client.py", line 898, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 1379, in get_connection
    connection.connect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 567, in connect
    self.on_connect()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 643, in on_connect
    auth_response = self.read_response()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 739, in read_response
    response = self._parser.read_response()
  File "/usr/lib/python2.7/site-packages/redis/connection.py", line 340, in read_response
    raise error
AuthenticationError: Client sent AUTH, but no password is set
2022-01-11 15:41:15,963 launcher.py[line:39] INFO exit!

**Comment by jhao104** [comment]
AuthenticationError: Client sent AUTH, but no password is set   配置正确密码
