### ISSUE TITLE
调度程序启动报错：KeyError: 'interval'

### ISSUE THREAD

**Issue by tcy941618** [jhao104/proxy_pool#634]
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 876, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'interval'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 32, in schedule
    startScheduler()
  File "/home/projects/proxy_pool/helper/launcher.py", line 32, in startScheduler
    runScheduler()
  File "/home/projects/proxy_pool/helper/scheduler.py", line 54, in runScheduler
    scheduler.add_job(__runProxyFetch, 'interval', minutes=4, id="proxy_fetch", name="proxy采集")
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 408, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 901, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 879, in _create_plugin_instance
    plugin_cls = class_container[alias] = plugin_container[alias].load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (zipp 0.6.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('zipp>=3.1.0; python_version < "3.10"'), {'importlib-resources'})

**Comment by tcy941618** [comment]
目测是这行代码报错的：
File "/home/projects/proxy_pool/helper/scheduler.py", line 54, in runScheduler
scheduler.add_job(__runProxyFetch, 'interval', minutes=4, id="proxy_fetch", name="proxy采集")
