### ISSUE TITLE
was trying to run the docker, got an error:

### ISSUE THREAD

**Issue by mmuncan1980** [jhao104/proxy_pool#636]
┌──(jamy㉿kali)-[~/Downloads/proxy_pool-2.4.0]
└─$ sudo docker run --env DB_CONN=redis://:password@ip:port/0 -p 5010:5010 jhao104/proxy_pool:2.4.0                                                                  126 ⨯
Unable to find image 'jhao104/proxy_pool:2.4.0' locally
2.4.0: Pulling from jhao104/proxy_pool
Digest: sha256:da98d8565ef8b1438fc47f7d83a86d8e25fc4540053fa9c02a599a7e98323d04
Status: Downloaded newer image for jhao104/proxy_pool:2.4.0

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2022-02-09 21:52:05,843 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-02-09 21:52:05,843 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-02-09 21:52:05,844 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-02-09 21:52:05,844 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-02-09 21:52:05,844 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-02-09 21:52:05,844 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-02-09 21:52:05,844 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-02-09 21:52:05,844 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 32, in schedule
    startScheduler()
  File "/app/helper/launcher.py", line 30, in startScheduler
    __beforeStart()
  File "/app/helper/launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "/app/helper/launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 56, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 64, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 172, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'
Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 39, in server
    startServer()
  File "/app/helper/launcher.py", line 24, in startServer
    __beforeStart()
  File "/app/helper/launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "/app/helper/launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 56, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 64, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 172, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'

**Comment by jhao104** [comment]
启动时的redis配置没有改，
如果没有redis的话，使用 `docker-compose up -d` 启动

**Comment by qqgreen** [comment]
> 启动时的redis配置没有改， 如果没有redis的话，使用 `docker-compose up -d` 启动

你好！请问“启动时的redis配置没有改”什么意思呢？该输入什么命令呢，小白不是很懂
