### ISSUE TITLE
docker无法启动

### ISSUE THREAD

**Issue by thank243** [jhao104/proxy_pool#644]
```docker logs
Traceback (most recent call last):
  File "run.py", line 1, in <module>
    from proxypool.scheduler import Scheduler
  File "/app/proxypool/scheduler.py", line 3, in <module>
    from proxypool.processors.server import app
  File "/app/proxypool/processors/server.py", line 1, in <module>
    from flask import Flask, g
  File "/root/.local/lib/python3.7/site-packages/flask/__init__.py", line 19, in <module>
    from . import json
  File "/root/.local/lib/python3.7/site-packages/flask/json/__init__.py", line 15, in <module>
    from itsdangerous import json as _json
ImportError: cannot import name 'json' from 'itsdangerous' (/root/.local/lib/python3.7/site-packages/itsdangerous/__init__.py)
```
无法从`itsdangerous` 导入json

**Comment by jhao104** [comment]
包的版本不兼容，项目的镜像是python3.6，更高版本的话三方模块可能就不兼容了，

**Comment by jhao104** [comment]
试试重装下itsdangerous模块，不指定版本

**Comment by MrMao14** [comment]
pip install Flask==1.1.4
执行以上命令即可解决
Flask升级他们已经删除了soft_unicode导致报错
给Flask强制降级
