### ISSUE TITLE
Python3 下运行报错，希望帮忙看下

### ISSUE THREAD

**Issue by weiyideai520** [jhao104/proxy_pool#65]
[root@iz8vbawf20vjywci9aweg8z Run]# python3 main.py
Process ValidRun:
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyValidSchedule.py", line 61, in run
    p.main()
  File "../Schedule/ProxyValidSchedule.py", line 56, in main
    self.__validProxy()
  File "../Schedule/ProxyValidSchedule.py", line 36, in __validProxy
    for each_proxy in self.db.getAll():
  File "../DB/DbClient.py", line 94, in getAll
    return self.client.getAll()
  File "/home/software/proxy_pool/DB/SsdbClient.py", line 94, in getAll
    return self.__conn.hgetall(self.name).keys()
  File "/usr/local/lib/python3.6/site-packages/ssdb-0.0.3-py3.6.egg/ssdb/client.py", line 1050, in hgetall
    return self.execute_command('hgetall', name)
  File "/usr/local/lib/python3.6/site-packages/ssdb-0.0.3-py3.6.egg/ssdb/client.py", line 225, in execute_command
    connection.send_command(*args)
  File "/usr/local/lib/python3.6/site-packages/ssdb-0.0.3-py3.6.egg/ssdb/connection.py", line 404, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/lib/python3.6/site-packages/ssdb-0.0.3-py3.6.egg/ssdb/connection.py", line 383, in send_packed_command
    self._sock.sendall(item)
TypeError: a bytes-like object is required, not 'str'

**Comment by forgic** [comment]
我是Python3.6，遇到一样的问题。
➜  Run git:(master) python main.py                                                         
Process ValidRun:
Traceback (most recent call last):
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/process.py", line 249, in _bootstrap
    self.run()
  File "/usr/local/python3.6/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyValidSchedule.py", line 61, in run
    p.main()
  File "../Schedule/ProxyValidSchedule.py", line 56, in main
    self.__validProxy()
  File "../Schedule/ProxyValidSchedule.py", line 36, in __validProxy
    for each_proxy in self.db.getAll():
  File "../DB/DbClient.py", line 94, in getAll
    return self.client.getAll()
  File "/proxy/proxy_pool/DB/SsdbClient.py", line 94, in getAll
    return self.__conn.hgetall(self.name).keys()
  File "/usr/local/python3.6/lib/python3.6/site-packages/ssdb/client.py", line 1043, in hgetall
    return self.execute_command('hgetall', name)
  File "/usr/local/python3.6/lib/python3.6/site-packages/ssdb/client.py", line 218, in execute_command
    connection.send_command(*args)
  File "/usr/local/python3.6/lib/python3.6/site-packages/ssdb/connection.py", line 404, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/usr/local/python3.6/lib/python3.6/site-packages/ssdb/connection.py", line 383, in send_packed_command
    self._sock.sendall(item)
TypeError: a bytes-like object is required, not 'str'

**Comment by jhao104** [comment]
这个ssdb这个扩展包兼容性不好，可以先暂时把ssdb有关方法比如hgetall 、hget方发传入的字符串参数转换成bytes型。后面会换掉这个库。
@forgic  @weiyideai520

**Comment by forgic** [comment]
作者您好，这个相信问题应该会有很多人遇到。请问有没有详细的修改教程，不然遇到会有些茫然无措

**Comment by jhao104** [comment]
@forgic 行吧  我中午更新下代码 :smile:

**Comment by forgic** [comment]
@jhao104 麻烦了，在线等

**Comment by jhao104** [comment]
@forgic  好了  之前用的ssdb驱动对py3不支持。 换了个repo

**Comment by forgic** [comment]
@jhao104 赞。  还有一个问题是启动脚本之后，ssdb数据库存在raw_proxy这个key，而且里面存储的是正确的数据，但是通过ip:5000/get_all取数据时候会返回空数组，试了两台服务器，不同的Python版本都存在同样的问题

**Comment by jhao104** [comment]
@forgic 看文档说明，raw_proxy是原始的代理， useful_proxy中的才是验证可用的代理
