### ISSUE TITLE
出错了

### ISSUE THREAD

**Issue by SkinAir** [jhao104/proxy_pool#659]
请问是我的python版本不兼容吗？

2022-04-29 16:29:55,957 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-04-29 16:29:55,957 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-04-29 16:29:55,957 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-04-29 16:29:55,958 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 39, in server
    startServer()
  File "/app/helper/launcher.py", line 24, in startServer
    __beforeStart()
  File "/app/helper/launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "/app/helper/launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 56, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 64, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 172, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'

**Comment by SkinAir** [comment]
或许是我docker 临时安装的redis的问题

**Comment by ClairJobs** [comment]
> 或许是我docker 临时安装的redis的问题

解决了么？我也遇到了这个问题

**Comment by jhao104** [comment]
```ValueError: invalid literal for int() with base 10: 'port'```
数据库配置有问题

**Comment by night-scale** [comment]
`ValueError: invalid literal for int() with base 10: 'port'`意思是将某个字符串参数转换为整型时出错，冒号后面的部分是尝试转换的字符串。显然这个参数是端口号之类的，检查一下是不是爬虫逻辑出错了，配置应该是没问题的
