### ISSUE TITLE
运行出错！

### ISSUE THREAD

**Issue by zhicheng233** [jhao104/proxy_pool#663]
配置好啦但是运行出错

**G:\MC\代理池\proxy_pool-2.4.0>python proxyPool.py server

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2022-05-08 13:51:53,984 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-05-08 13:51:53,984 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-05-08 13:51:53,984 launcher.py[line:51] INFO ProxyPool configure PORT: 4719
2022-05-08 13:51:53,985 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-05-08 13:51:54,069 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-05-08 13:51:54,070 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-05-08 13:51:54,070 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2022-05-08 13:51:54,070 launcher.py[line:61] INFO DB_PORT: 6379
2022-05-08 13:51:54,070 launcher.py[line:62] INFO DB_NAME: 0
2022-05-08 13:51:54,070 launcher.py[line:63] INFO DB_USER:
2022-05-08 13:51:54,070 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "G:\MC\代理池\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "I:\Python 3.10\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "I:\Python 3.10\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "I:\Python 3.10\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "I:\Python 3.10\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "I:\Python 3.10\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "G:\MC\代理池\proxy_pool-2.4.0\proxyPool.py", line 39, in server
    startServer()
  File "G:\MC\代理池\proxy_pool-2.4.0\helper\launcher.py", line 25, in startServer
    from api.proxyApi import runFlask
  File "G:\MC\代理池\proxy_pool-2.4.0\api\proxyApi.py", line 20, in <module>
    from flask import Flask, jsonify, request
  File "I:\Python 3.10\lib\site-packages\flask\__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (I:\Python 3.10\lib\site-packages\jinja2\__init__.py)**

**Comment by jhao104** [comment]
python版本太高了，目前支持到3.6.   3.6以上的版本把requirements.txt里面的版本号删掉 重新pip install 一下

**Comment by zhicheng233** [comment]
> python版本太高了，目前支持到3.6.   3.6以上的版本把requirements.txt里面的版本号删掉 重新pip install 一下

好的谢谢
