### ISSUE TITLE
运行 `python proxyPool.py server` 出错

### ISSUE THREAD

**Issue by zhangxiann** [jhao104/proxy_pool#668]
按照 readme 一步一步操作的。
运行到 `python proxyPool.py server` 出错

```

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2022-05-22 18:41:46,207 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-05-22 18:41:46,207 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-05-22 18:41:46,207 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-05-22 18:41:46,207 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-05-22 18:41:46,268 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-05-22 18:41:46,268 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-05-22 18:41:46,268 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2022-05-22 18:41:46,268 launcher.py[line:61] INFO DB_PORT: 6379
2022-05-22 18:41:46,268 launcher.py[line:62] INFO DB_NAME: 0
2022-05-22 18:41:46,268 launcher.py[line:63] INFO DB_USER: 
2022-05-22 18:41:46,268 launcher.py[line:64] INFO =================================================
2022-05-22 18:41:46,270 redisClient.py[line:149] ERROR redis connection error: Error 61 connecting to 127.0.0.1:6379. Connection refused.
Traceback (most recent call last):
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 614, in connect
    sock = self.retry.call_with_retry(
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/retry.py", line 46, in call_with_retry
    return do()
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 615, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 680, in _connect
    raise err
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 668, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/jufryzhang/Desktop/Project/proxy_pool/db/redisClient.py", line 144, in test
    self.getCount()
  File "/Users/jufryzhang/Desktop/Project/proxy_pool/db/redisClient.py", line 130, in getCount
    proxies = self.getAll(https=False)
  File "/Users/jufryzhang/Desktop/Project/proxy_pool/db/redisClient.py", line 112, in getAll
    items = self.__conn.hvals(self.name)
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/commands/core.py", line 4914, in hvals
    return self.execute_command("HVALS", name)
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/client.py", line 1224, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 1587, in get_connection
    connection.connect()
  File "/Users/jufryzhang/opt/anaconda3/lib/python3.9/site-packages/redis/connection.py", line 620, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:6379. Connection refused.
2022-05-22 18:41:46,273 launcher.py[line:39] INFO exit!
```

**Comment by zywxzh6** [comment]
Redis 服务没启动

**Comment by zhangxiann** [comment]
> Redis 服务没启动

怎么操作？我看了 readme 和 文档，没有这个东西

**Comment by zywxzh6** [comment]
他代码里有，爬下来的代理地址都存在redis 里了，你安装个r
edis，网上很多配置教程，地址和端口就显示的那个
