### ISSUE TITLE
docker 啟動出錯

### ISSUE THREAD

**Issue by CubatLin** [jhao104/proxy_pool#670]
成功拉下latest, 但啟動部分有問題～
```
docker run --env DB_CONN=redis://:password@ip:port/0 -p 5010:5010 jhao104/proxy_pool:2.4.0
Using default tag: latest
latest: Pulling from jhao104/proxy_pool
59bf1c3509f3: Pull complete 
8786870f2876: Pull complete 
acb0e804800e: Pull complete 
52bedcb3e853: Pull complete 
b064415ed3d7: Pull complete 
1fa7f6e24da4: Pull complete 
97a37ac4afa4: Pull complete 
af3a6f89994d: Pull complete 
7ddc19cab27b: Pull complete 
cc4cec4bfd29: Pull complete 
89e9cf2ce693: Pull complete 
Digest: sha256:da98d8565ef8b1438fc47f7d83a86d8e25fc4540053fa9c02a599a7e98323d04
Status: Downloaded newer image for jhao104/proxy_pool:latest
docker.io/jhao104/proxy_pool:latest
Unable to find image 'jhao104/proxy_pool:2.4.0' locally
2.4.0: Pulling from jhao104/proxy_pool
Digest: sha256:da98d8565ef8b1438fc47f7d83a86d8e25fc4540053fa9c02a599a7e98323d04
Status: Downloaded newer image for jhao104/proxy_pool:2.4.0
WARNING: The requested image's platform (linux/amd64) does not match the detected host platform (linux/arm64/v8) and no specific platform was requested

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************


****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2022-05-26 14:40:14,562 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-05-26 14:40:14,562 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-05-26 14:40:14,565 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-05-26 14:40:14,566 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-05-26 14:40:14,566 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-05-26 14:40:14,567 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-05-26 14:40:14,567 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-05-26 14:40:14,568 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 32, in schedule
    startScheduler()
  File "/app/helper/launcher.py", line 30, in startScheduler
    __beforeStart()
  File "/app/helper/launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "/app/helper/launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 56, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 64, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 172, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'
Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 39, in server
    startServer()
  File "/app/helper/launcher.py", line 24, in startServer
    __beforeStart()
  File "/app/helper/launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "/app/helper/launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "/app/util/singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "/app/db/dbClient.py", line 56, in __init__
    self.parseDbConn(db_conn)
  File "/app/db/dbClient.py", line 64, in parseDbConn
    cls.db_port = db_conf.port
  File "/usr/local/lib/python3.6/urllib/parse.py", line 172, in port
    port = int(port, 10)
ValueError: invalid literal for int() with base 10: 'port'
```

**Comment by tabs** [comment]
你也不能完全抄啊兄弟 redis IP 端口不带变的吗
