### ISSUE TITLE
小白请教下前辈们，python proxyPool.py schedule后报错，显示redis invalid password？

### ISSUE THREAD

**Issue by JTP-123** [jhao104/proxy_pool#672]
这是运行后得，报错
---
2022-06-06 14:29:10,955 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-06-06 14:29:10,955 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-06-06 14:29:10,955 launcher.py[line:51] INFO ProxyPool configure PORT: 5000
2022-06-06 14:29:10,955 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-06-06 14:29:11,024 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-06-06 14:29:11,024 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-06-06 14:29:11,024 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2022-06-06 14:29:11,024 launcher.py[line:61] INFO DB_PORT: 6379
2022-06-06 14:29:11,024 launcher.py[line:62] INFO DB_NAME: 0
2022-06-06 14:29:11,024 launcher.py[line:63] INFO DB_USER:
2022-06-06 14:29:11,024 launcher.py[line:64] INFO =================================================
2022-06-06 14:29:11,024 redisClient.py[line:149] ERROR redis connection error: invalid password
Traceback (most recent call last):
  File "C:\Users\sky\python_work\proxy_pool-2.4.0\db\redisClient.py", line 144, in test
    self.getCount()
  File "C:\Users\sky\python_work\proxy_pool-2.4.0\db\redisClient.py", line 130, in getCount
    proxies = self.getAll(https=False)
  File "C:\Users\sky\python_work\proxy_pool-2.4.0\db\redisClient.py", line 112, in getAll
    items = self.__conn.hvals(self.name)
  File "D:\program\python\lib\site-packages\redis\commands\core.py", line 4914, in hvals
    return self.execute_command("HVALS", name)
  File "D:\program\python\lib\site-packages\redis\client.py", line 1224, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "D:\program\python\lib\site-packages\redis\connection.py", line 1587, in get_connection
    connection.connect()
  File "D:\program\python\lib\site-packages\redis\connection.py", line 626, in connect
    self.on_connect()
  File "D:\program\python\lib\site-packages\redis\connection.py", line 716, in on_connect
    auth_response = self.read_response()
  File "D:\program\python\lib\site-packages\redis\connection.py", line 827, in read_response
    response = self._parser.read_response(disable_decoding=disable_decoding)
  File "D:\program\python\lib\site-packages\redis\connection.py", line 336, in read_response
    raise error
redis.exceptions.AuthenticationError: invalid password
2022-06-06 14:29:11,024 launcher.py[line:39] INFO exit!
--- 
这是链接redis后的

D:\program\redis>redis-server.exe D:\program\redis\redis.windows.conf
                _._
           _.-``__ ''-._
      _.-``    `.  `_.  ''-._           Redis 3.2.100 (00000000/0) 64 bit
  .-`` .-```.  ```\/    _.,_ ''-._
 (    '      ,       .-`  | `,    )     Running in standalone mode
 |`-._`-...-` __...-.``-._|'` _.-'|     Port: 6379
 |    `-._   `._    /     _.-'    |     PID: 26432
  `-._    `-._  `-./  _.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |           http://redis.io
  `-._    `-._`-.__.-'_.-'    _.-'
 |`-._`-._    `-.__.-'    _.-'_.-'|
 |    `-._`-._        _.-'_.-'    |
  `-._    `-._`-.__.-'_.-'    _.-'
      `-._    `-.__.-'    _.-'
          `-._        _.-'
              `-.__.-'

[26432] 06 Jun 14:13:26.084 # Server started, Redis version 3.2.100
[26432] 06 Jun 14:13:26.084 * DB loaded from disk: 0.000 seconds
[26432] 06 Jun 14:13:26.084 * The server is now ready to accept connections on port 6379

**Comment by jhao104** [comment]
redis如果有特殊符号需要转义

**Comment by JTP-123** [comment]
您好，redis密码就是普通的 123456, auth ‘123456’ 也ok的。

现实是老师，梦中是学生

发件人: ***@***.***>
发送时间: 2022年6月8日 9:54
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: Re: [jhao104/proxy_pool] 小白请教下前辈们，python proxyPool.py schedule后报错，显示redis invalid password？ (Issue #672)


redis密码如果有特殊符号需要转义

―

**Comment by plantonic** [comment]
请问您解决了吗，我也遇到了相似的问题？

**Comment by JTP-123** [comment]
> 请问您解决了吗，我也遇到了相似的问题？

您可以看下密码是否正确
