### ISSUE TITLE
requirements.txt需要更新

### ISSUE THREAD

**Issue by k-a-2000** [jhao104/proxy_pool#680]
pip install -r requirements.txt
安装之后
python proxyPool.py schedule
成功
python proxyPool.py server
报错
      Traceback (most recent call last):
        File "proxyPool.py", line 43, in <module>
          cli()
        File "/root/anaconda3/envs/proxy/lib/python3.8/site-packages/click/core.py", line 764, in __call__
          return self.main(*args, **kwargs)
        File "/root/anaconda3/envs/proxy/lib/python3.8/site-packages/click/core.py", line 717, in main
          rv = self.invoke(ctx)
        File "/root/anaconda3/envs/proxy/lib/python3.8/site-packages/click/core.py", line 1137, in invoke
          return _process_result(sub_ctx.command.invoke(sub_ctx))
        File "/root/anaconda3/envs/proxy/lib/python3.8/site-packages/click/core.py", line 956, in invoke
          return ctx.invoke(self.callback, **ctx.params)
        File "/root/anaconda3/envs/proxy/lib/python3.8/site-packages/click/core.py", line 555, in invoke
          return callback(*args, **kwargs)
        File "proxyPool.py", line 39, in server
          startServer()
        File "/root/proxy_pool-master/helper/launcher.py", line 25, in startServer
          from api.proxyApi import runFlask
        File "/root/proxy_pool-master/api/proxyApi.py", line 20, in <module>
          from flask import Flask, jsonify, request
        File "/root/anaconda3/envs/proxy/lib/python3.8/site-packages/flask/__init__.py", line 19, in <module>
          from jinja2 import Markup, escape
      ImportError: cannot import name 'Markup' from 'jinja2' (/root/anaconda3/envs/proxy/lib/python3.8/site-packages/jinja2/__init__.py)

pip install flask==2.0.2
安装后成功

**Comment by jhao104** [comment]
现在支持3.6版本以下的， 以上的没有验证过

**Comment by k-a-2000** [comment]
好的
