### ISSUE TITLE
运行python proxyPool.py server报错，兄弟们救我一下，我真的会谢，栓Q

### ISSUE THREAD

**Issue by aixinjueluolaoba** [jhao104/proxy_pool#681]
****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2022-07-12 09:24:16,517 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-07-12 09:24:16,518 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-07-12 09:24:16,518 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-07-12 09:24:16,518 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-07-12 09:24:16,577 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-07-12 09:24:16,578 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-07-12 09:24:16,578 launcher.py[line:60] INFO DB_HOST: None
2022-07-12 09:24:16,579 launcher.py[line:61] INFO DB_PORT: None
2022-07-12 09:24:16,580 launcher.py[line:62] INFO DB_NAME: :@/127.0.0.1:6379/0
2022-07-12 09:24:16,581 launcher.py[line:63] INFO DB_USER: None
2022-07-12 09:24:16,582 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "/home/lighthouse/proxy_pool-2.4.0/proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/dist-packages/click/core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "/home/lighthouse/proxy_pool-2.4.0/proxyPool.py", line 39, in server
    startServer()
  File "/home/lighthouse/proxy_pool-2.4.0/helper/launcher.py", line 24, in startServer
    __beforeStart()
  File "/home/lighthouse/proxy_pool-2.4.0/helper/launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "/home/lighthouse/proxy_pool-2.4.0/helper/launcher.py", line 65, in __checkDBConfig
    return db.test()
  File "/home/lighthouse/proxy_pool-2.4.0/db/dbClient.py", line 120, in test
    return self.client.test()
  File "/home/lighthouse/proxy_pool-2.4.0/db/redisClient.py", line 144, in test
    self.getCount()
  File "/home/lighthouse/proxy_pool-2.4.0/db/redisClient.py", line 130, in getCount
    proxies = self.getAll(https=False)
  File "/home/lighthouse/proxy_pool-2.4.0/db/redisClient.py", line 112, in getAll
    items = self.__conn.hvals(self.name)
  File "/usr/local/lib/python3.9/dist-packages/redis/commands/core.py", line 4887, in hvals
    return self.execute_command("HVALS", name)
  File "/usr/local/lib/python3.9/dist-packages/redis/client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1578, in get_connection
    connection = self.make_connection()
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 1546, in make_connection
    connection = self.connection_class(**self.connection_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/redis/connection.py", line 539, in __init__
    self.port = int(port)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

**Comment by jhao104** [comment]
redis的db配置问题 应该是一个数字 0到14
