### ISSUE TITLE
启动不了调度,按着步骤来的

### ISSUE THREAD

**Issue by mcjie** [jhao104/proxy_pool#686]
2022-08-02 22:58:57,817 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-08-02 22:58:57,817 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2022-08-02 22:58:57,817 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-08-02 22:58:57,817 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-08-02 22:58:57,990 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-08-02 22:58:57,990 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-08-02 22:58:57,990 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2022-08-02 22:58:57,990 launcher.py[line:61] INFO DB_PORT: 6379
2022-08-02 22:58:57,990 launcher.py[line:62] INFO DB_NAME: 0
2022-08-02 22:58:57,990 launcher.py[line:63] INFO DB_USER:
2022-08-02 22:58:57,990 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "D:\zhw\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\zhw\proxy_pool-2.4.0\proxyPool.py", line 32, in schedule
    startScheduler()
  File "D:\zhw\proxy_pool-2.4.0\helper\launcher.py", line 31, in startScheduler
    from helper.scheduler import runScheduler
  File "D:\zhw\proxy_pool-2.4.0\helper\scheduler.py", line 16, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\apscheduler\schedulers\blocking.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler, STATE_STOPPED
  File "D:\Program Files (x86)\Python 3.10.5\lib\site-packages\apscheduler\schedulers\base.py", line 4, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (D:\Program Files (x86)\Python 3.10.5\lib\collections\__init__.py)

**Comment by jhao104** [comment]
使用Python3.6

**Comment by tcotu** [comment]
shell:
[root@VM-8-2-centos 175.178.67.144]# python3
Python 3.6.8 (default, Sep 10 2021, 09:13:53) 
[GCC 8.5.0 20210514 (Red Hat 8.5.0-3)] on linux
Type "help", "copyright", "credits" or "license" for more information.

log:
2022-08-08 18:24:29,225 check.py[line:90] INFO RawProxyCheck - thread_18: complete
2022-08-08 18:24:35,486 check.py[line:102] INFO RawProxyCheck - thread_03: 124.204.33.162:8000     exist
2022-08-08 18:24:35,486 check.py[line:90] INFO RawProxyCheck - thread_03: complete
Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 876, in _create_plugin_instance
    plugin_cls = class_container[alias]
KeyError: 'interval'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib64/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 32, in schedule
    startScheduler()
  File "/www/wwwroot/175.178.67.144/helper/launcher.py", line 32, in startScheduler
    runScheduler()
  File "/www/wwwroot/175.178.67.144/helper/scheduler.py", line 54, in runScheduler
    scheduler.add_job(__runProxyFetch, 'interval', minutes=4, id="proxy_fetch", name="proxy采集")
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 408, in add_job
    'trigger': self._create_trigger(trigger, trigger_args),
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 901, in _create_trigger
    return self._create_plugin_instance('trigger', trigger, trigger_args)
  File "/usr/local/lib/python3.6/site-packages/apscheduler/schedulers/base.py", line 879, in _create_plugin_instance
    plugin_cls = class_container[alias] = plugin_container[alias].load()
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2317, in load
    self.require(*args, **kwargs)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 2340, in require
    items = working_set.resolve(reqs, env, installer, extras=self.extras)
  File "/usr/lib/python3.6/site-packages/pkg_resources/__init__.py", line 779, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (zipp 0.6.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('zipp>=3.1.0; python_version < "3.10"'), {'importlib-resources'})

**Comment by tcotu** [comment]
same question,i think something not compatible

**Comment by jhao104** [comment]
@tcotu 
```
pkg_resources.ContextualVersionConflict: (zipp 0.6.0 (/usr/local/lib/python3.6/site-packages), Requirement.parse('zipp>=3.1.0; python_version < "3.10"'), {'importlib-resources'})
```
看报错信息啊， 三方包版本不兼容
