### ISSUE TITLE
请教各位前辈

### ISSUE THREAD

**Issue by xy0893** [jhao104/proxy_pool#700]
请教各位前辈为什么我连接错误

2022-08-29 19:02:13,362 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2022-08-29 19:02:13,362 launcher.py[line:50] INFO ProxyPool configure HOST: 127.0.0.1
2022-08-29 19:02:13,377 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2022-08-29 19:02:13,377 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2022-08-29 19:02:13,533 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2022-08-29 19:02:13,533 launcher.py[line:59] INFO DB_TYPE: REDIS
2022-08-29 19:02:13,533 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2022-08-29 19:02:13,533 launcher.py[line:61] INFO DB_PORT: 6379
2022-08-29 19:02:13,533 launcher.py[line:62] INFO DB_NAME: 0
2022-08-29 19:02:13,533 launcher.py[line:63] INFO DB_USER:
2022-08-29 19:02:13,533 launcher.py[line:64] INFO =================================================
2022-08-29 19:02:14,553 redisClient.py[line:149] ERROR redis connection error: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.
Traceback (most recent call last):
  File "C:\python3\lib\site-packages\redis\connection.py", line 611, in connect
    sock = self.retry.call_with_retry(
  File "C:\python3\lib\site-packages\redis\retry.py", line 46, in call_with_retry
    return do()
  File "C:\python3\lib\site-packages\redis\connection.py", line 612, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
  File "C:\python3\lib\site-packages\redis\connection.py", line 677, in _connect
    raise err
  File "C:\python3\lib\site-packages\redis\connection.py", line 665, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [WinError 10061] 由于目标计算机积极拒绝，无法连接。

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\libai\Desktop\proxy_pool-2.4.0\db\redisClient.py", line 144, in test
    self.getCount()
  File "C:\Users\libai\Desktop\proxy_pool-2.4.0\db\redisClient.py", line 130, in getCount
    proxies = self.getAll(https=False)
  File "C:\Users\libai\Desktop\proxy_pool-2.4.0\db\redisClient.py", line 112, in getAll
    items = self.__conn.hvals(self.name)
  File "C:\python3\lib\site-packages\redis\commands\core.py", line 4887, in hvals
    return self.execute_command("HVALS", name)
  File "C:\python3\lib\site-packages\redis\client.py", line 1235, in execute_command
    conn = self.connection or pool.get_connection(command_name, **options)
  File "C:\python3\lib\site-packages\redis\connection.py", line 1582, in get_connection
    connection.connect()
  File "C:\python3\lib\site-packages\redis\connection.py", line 617, in connect
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 10061 connecting to 127.0.0.1:6379. 由于目标计算机积极拒绝，无法连接。.
2022-08-29 19:02:14,553 launcher.py[line:39] INFO exit

**Comment by xy0893** [comment]
![image](https://user-images.githubusercontent.com/80501650/187193203-7f9b7051-5baf-4f98-96db-3a23f5d941e2.png)
实在是不知道怎么配置了， 提示密码错误，我试着把pwd 删掉还是报错

**Comment by jhao104** [comment]
没有密码的话就是redis://@ip:port/db

**Comment by xy0893** [comment]
感谢开发大佬的回复。   不过我依然没有解决该问题
![image](https://user-images.githubusercontent.com/80501650/188301400-a8bbe626-2645-4129-a3f6-b4b199e2bf06.png)
标注红色区域进行了修改尝试启动依旧报错，黄色标注区域尝试去掉# 去掉password启动依旧报错！

**Comment by jhao104** [comment]
@xy0893 你要学会看报错， 最后一句说的是 invalid DB index.  
`redis://@ip:port/db` 这里的db是redis的库，0到15的数字。
