### ISSUE TITLE
'dict' object has no attribute 'decode'

### ISSUE THREAD

**Issue by 2445546** [jhao104/proxy_pool#709]
![图片](https://user-images.githubusercontent.com/100853631/204329949-54a1e21c-009a-4ea0-99d0-8ee5f16745ef.png)
Traceback (most recent call last):
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "D:\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "D:\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "D:\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "D:\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "D:\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\proxyPool.py", line 32, in schedule
    startScheduler()
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\helper\launcher.py", line 30, in startScheduler
    __beforeStart()
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\helper\launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\helper\launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\util\singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\db\dbClient.py", line 56, in __init__
    self.parseDbConn(db_conn)
  File "D:\Desktop\SafeArmory1.0\proxy_pool-2.4.0\db\dbClient.py", line 61, in parseDbConn
    db_conf = urlparse(db_conn)
  File "D:\python39\lib\urllib\parse.py", line 392, in urlparse
    url, scheme, _coerce_result = _coerce_args(url, scheme)
  File "D:\python39\lib\urllib\parse.py", line 128, in _coerce_args
    return _decode_args(args) + (_encode_result,)
  File "D:\python39\lib\urllib\parse.py", line 112, in _decode_args
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
  File "D:\python39\lib\urllib\parse.py", line 112, in <genexpr>
    return tuple(x.decode(encoding, errors) if x else '' for x in args)
AttributeError: 'dict' object has no attribute 'decode'

**Comment by jhao104** [comment]
配置问题，db_conn是字符串
