### ISSUE TITLE
我不能启动程序

### ISSUE THREAD

**Issue by Aknices-QWQ** [jhao104/proxy_pool#713]
```
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 如果已经具备运行条件, 可用通过proxyPool.py启动。
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 程序分为: schedule 调度程序 和 server Api服务
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0>
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 启动调度程序
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> python proxyPool.py schedule

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2023-01-05 21:49:12,287 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2023-01-05 21:49:12,287 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2023-01-05 21:49:12,288 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2023-01-05 21:49:12,289 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2023-01-05 21:49:12,434 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2023-01-05 21:49:12,434 launcher.py[line:59] INFO DB_TYPE: REDIS
2023-01-05 21:49:12,434 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2023-01-05 21:49:12,434 launcher.py[line:61] INFO DB_PORT: 1145
2023-01-05 21:49:12,435 launcher.py[line:62] INFO DB_NAME: 0
2023-01-05 21:49:12,435 launcher.py[line:63] INFO DB_USER:
2023-01-05 21:49:12,435 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 32, in schedule
    startScheduler()
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\helper\launcher.py", line 31, in startScheduler
    from helper.scheduler import runScheduler
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\helper\scheduler.py", line 16, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\schedulers\blocking.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler, STATE_STOPPED
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\schedulers\base.py", line 4, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0>
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 启动webApi服务
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> python proxyPool.py server

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2023-01-05 21:49:12,863 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2023-01-05 21:49:12,863 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2023-01-05 21:49:12,863 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2023-01-05 21:49:12,864 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2023-01-05 21:49:13,007 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2023-01-05 21:49:13,007 launcher.py[line:59] INFO DB_TYPE: REDIS
2023-01-05 21:49:13,009 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2023-01-05 21:49:13,009 launcher.py[line:61] INFO DB_PORT: 1145
2023-01-05 21:49:13,009 launcher.py[line:62] INFO DB_NAME: 0
2023-01-05 21:49:13,009 launcher.py[line:63] INFO DB_USER:
2023-01-05 21:49:13,009 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 39, in server
    startServer()
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\helper\launcher.py", line 25, in startServer
    from api.proxyApi import runFlask
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\api\proxyApi.py", line 20, in <module>
    from flask import Flask, jsonify, request
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\__init__.py)
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0>
```
'''

**Comment by Aknices-QWQ** [comment]
```
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 如果已经具备运行条件, 可用通过proxyPool.py启动。
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 程序分为: schedule 调度程序 和 server Api服务
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0>
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 启动调度程序
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> python proxyPool.py schedule

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2023-01-05 21:49:12,287 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2023-01-05 21:49:12,287 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2023-01-05 21:49:12,288 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2023-01-05 21:49:12,289 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2023-01-05 21:49:12,434 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2023-01-05 21:49:12,434 launcher.py[line:59] INFO DB_TYPE: REDIS
2023-01-05 21:49:12,434 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2023-01-05 21:49:12,434 launcher.py[line:61] INFO DB_PORT: 1145
2023-01-05 21:49:12,435 launcher.py[line:62] INFO DB_NAME: 0
2023-01-05 21:49:12,435 launcher.py[line:63] INFO DB_USER:
2023-01-05 21:49:12,435 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 32, in schedule
    startScheduler()
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\helper\launcher.py", line 31, in startScheduler
    from helper.scheduler import runScheduler
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\helper\scheduler.py", line 16, in <module>
    from apscheduler.schedulers.blocking import BlockingScheduler
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\schedulers\blocking.py", line 5, in <module>
    from apscheduler.schedulers.base import BaseScheduler, STATE_STOPPED
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\apscheduler\schedulers\base.py", line 4, in <module>
    from collections import MutableMapping
ImportError: cannot import name 'MutableMapping' from 'collections' (C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\collections\__init__.py)
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0>
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> # 启动webApi服务
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0> python proxyPool.py server

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2023-01-05 21:49:12,863 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2023-01-05 21:49:12,863 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2023-01-05 21:49:12,863 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2023-01-05 21:49:12,864 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
2023-01-05 21:49:13,007 launcher.py[line:58] INFO ============ DATABASE CONFIGURE ================
2023-01-05 21:49:13,007 launcher.py[line:59] INFO DB_TYPE: REDIS
2023-01-05 21:49:13,009 launcher.py[line:60] INFO DB_HOST: 127.0.0.1
2023-01-05 21:49:13,009 launcher.py[line:61] INFO DB_PORT: 1145
2023-01-05 21:49:13,009 launcher.py[line:62] INFO DB_NAME: 0
2023-01-05 21:49:13,009 launcher.py[line:63] INFO DB_USER:
2023-01-05 21:49:13,009 launcher.py[line:64] INFO =================================================
Traceback (most recent call last):
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 43, in <module>
    cli()
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
         ^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\proxyPool.py", line 39, in server
    startServer()
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\helper\launcher.py", line 25, in startServer
    from api.proxyApi import runFlask
  File "C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0\api\proxyApi.py", line 20, in <module>
    from flask import Flask, jsonify, request
  File "C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\flask\__init__.py", line 19, in <module>
    from jinja2 import Markup, escape
ImportError: cannot import name 'Markup' from 'jinja2' (C:\Users\aknic\AppData\Local\Programs\Python\Python311\Lib\site-packages\jinja2\__init__.py)
PS C:\Users\aknic\Documents\NOChinese\proxy_pool-2.4.0>
```

**Comment by xswwxx** [comment]
需要安装联系QQ8608037

**Comment by bitjerry** [comment]
更新所有的库或者降级你的python版本
这个错误是由于新版python某些内置库的api改变造成的, 作者的requirements.txt里的版本号已经很老了

**Comment by jhao104** [comment]
已更新requirements.txt
