### ISSUE TITLE
不停报错

### ISSUE THREAD

**Issue by djme0** [jhao104/proxy_pool#755]
C:\Users\29945\Desktop\pool\proxy_pool-2.4.1>python proxyPool.py schedule

****************************************************************
*** ______  ********************* ______ *********** _  ********
*** | ___ \_ ******************** | ___ \ ********* | | ********
*** | |_/ / \__ __   __  _ __   _ | |_/ /___ * ___  | | ********
*** |  __/|  _// _ \ \ \/ /| | | ||  __// _ \ / _ \ | | ********
*** | |   | | | (_) | >  < \ |_| || |  | (_) | (_) || |___  ****
*** \_|   |_|  \___/ /_/\_\ \__  |\_|   \___/ \___/ \_____/ ****
****                       __ / /                          *****
************************* /___ / *******************************
*************************       ********************************
****************************************************************

2023-06-21 21:29:34,668 launcher.py[line:45] INFO ProxyPool Version: 2.4.0
2023-06-21 21:29:34,669 launcher.py[line:50] INFO ProxyPool configure HOST: 0.0.0.0
2023-06-21 21:29:34,669 launcher.py[line:51] INFO ProxyPool configure PORT: 5010
2023-06-21 21:29:34,671 launcher.py[line:52] INFO ProxyPool configure PROXY_FETCHER: ['freeProxy01', 'freeProxy02', 'freeProxy03', 'freeProxy04', 'freeProxy05', 'freeProxy06', 'freeProxy07', 'freeProxy08', 'freeProxy09', 'freeProxy10']
Traceback (most recent call last):
  File "proxyPool.py", line 43, in <module>
    cli()
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 717, in main
    rv = self.invoke(ctx)
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\click\core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "proxyPool.py", line 32, in schedule
    startScheduler()
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\helper\launcher.py", line 30, in startScheduler
    __beforeStart()
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\helper\launcher.py", line 38, in __beforeStart
    if __checkDBConfig():
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\helper\launcher.py", line 57, in __checkDBConfig
    db = DbClient(conf.dbConn)
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\util\singleton.py", line 25, in __call__
    cls._inst[cls] = super(Singleton, cls).__call__(*args)
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\db\dbClient.py", line 57, in __init__
    self.__initDbClient()
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\db\dbClient.py", line 83, in __initDbClient
    self.client = getattr(__import__(__type), "%sClient" % self.db_type.title())(host=self.db_host,
  File "C:\Users\29945\Desktop\pool\proxy_pool-2.4.1\db\redisClient.py", line 17, in <module>
    from redis.exceptions import TimeoutError, ConnectionError, ResponseError
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\redis\__init__.py", line 3, in <module>
    from redis.client import Redis, StrictRedis
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\redis\client.py", line 9, in <module>
    from redis.commands import (
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\redis\commands\__init__.py", line 1, in <module>
    from .cluster import READ_COMMANDS, AsyncRedisClusterCommands, RedisClusterCommands
  File "C:\Users\29945\AppData\Local\Programs\Python\Python36\lib\site-packages\redis\commands\cluster.py", line 2, in <module>
    from typing import (
ImportError: cannot import name 'NoReturn'

**Comment by oritert** [comment]
why
