### ISSUE TITLE
国内服务器搭建正常，可是在国个服务器一样搭建就报错了。哪里可以优化下....

### ISSUE THREAD

**Issue by lenlin** [jhao104/proxy_pool#76]
2017-10-16 00:18:54,134 ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy 111.62.245.195:8321
2017-10-16 00:18:54,135 ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy 180.173.52.202:9045
2017-10-16 00:18:54,135 ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy 42.245.252.35:8345
2017-10-16 00:18:54,137 ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy 183.2.208.35:8575
2017-10-16 00:18:54,137 ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy 210.38.1.146:8463
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
('Connection aborted.', error(104, 'Connection reset by peer'))
Process RefreshRun:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 96, in run
    main()
  File "../Schedule/ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 45, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "../ProxyGetter/getFreeProxy.py", line 71, in freeProxySecond
    html = request.get(url).text
AttributeError: 'NoneType' object has no attribute 'text'

**Comment by jhao104** [comment]
@lenlin  国外的服务器 你的确认这几个代理网站能在服务器上正常访问。不然会报错。你这个把freeProxySecond注释掉就可以了。 确实，这个问题应该以更友好的方式处理

**Comment by lenlin** [comment]
查询报错信息，可能是频繁请求的问题，是不是可以设下headers，配置断开连接后自动重连。我在Config.ini里把freeProxyFirst  = 0 再运行它还是跑ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy。。奇怪

**Comment by jhao104** [comment]
@lenlin freeProxyFirst 这个网站改版了， 还没有时间去改这个代码 :disappointed_relieved:

**Comment by lenlin** [comment]
我在Config.ini里把freeProxyFirst = 0  
在getFreeProxy.py把
`#    def freeProxyFirst(page=10):`
`##        """`
`#        抓取无忧代理 http://www.data5u.com/`
`#        :param page: 页数
`#        :return:
`#        """
`#        url_list = ['http://www.data5u.com/',
`#                    'http://www.data5u.com/free/',
`#                    'http://www.data5u.com/free/gngn/index.shtml',
`#                    'http://www.data5u.com/free/gnpt/index.shtml']
`#        for url in url_list:
`#            html_tree = getHtmlTree(url)
`#            ul_list = html_tree.xpath('//ul[@class="l2"]')
`#            for ul in ul_list:
`#                yield ':'.join(ul.xpath('.//li/text()')[0:2])

运行报错。
root@localhost:/home/proxy_pool/Run# python main.py                   
Process RefreshRun:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 96, in run
    main()
  File "../Schedule/ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 45, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
AttributeError: type object 'GetFreeProxy' has no attribute 'freeProxyFirst'

**Comment by jhao104** [comment]
@lenlin 是修改Config.ini 
GetFreeProxy这个网站该版本，规则变了，要么你修改规则修复解析bug。要么就注释掉Config.ini中的GetFreeProxy 或者设置为0

**Comment by lenlin** [comment]
可以优化伪装成浏览器访问。

**Comment by jhao104** [comment]
@lenlin 现在是这样的

**Comment by lenlin** [comment]
为什么我在Config.ini 把freeProxyFirst  = 0
再启动还是会报错HTTPConnectionPool(host='www.data5u.com', port=80): Max retries exceeded with url: / (Caused by ConnectTimeoutError(<requests.packages.urllib3.connection.HTTPConnection object at 0x1aa9d50>, 'Connection to www.data5u.com timed out. (connect timeout=30)'))

**Comment by jhao104** [comment]
@lenlin 把freeProxyFirst = 0注释或者删掉试试
