### ISSUE TITLE
启动后报错

### ISSUE THREAD

**Issue by power255** [jhao104/proxy_pool#81]
Ubuntu  1710   配置没有改过
2017-11-04 16:07:00,270 ProxyManager.py[line:47] INFO freeProxyFirst: fetch proxy 27.36.116.226:8972
Process RefreshRun:
Traceback (most recent call last):
  File "/usr/lib/python2.7/multiprocessing/process.py", line 267, in _bootstrap
    self.run()
  File "/usr/lib/python2.7/multiprocessing/process.py", line 114, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 96, in run
    main()
  File "../Schedule/ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 53, in refresh
    if self.db.exists(proxy):
  File "../DB/DbClient.py", line 93, in exists
    return self.client.exists(key, **kwargs)
  File "/home/yg/py/proxy_pool-master/DB/SsdbClient.py", line 95, in exists
    return self.__conn.hexists(self.name, key)
  File "/home/yg/.local/lib/python2.7/site-packages/redis/client.py", line 1853, in hexists
    return self.execute_command('HEXISTS', name, key)
  File "/home/yg/.local/lib/python2.7/site-packages/redis/client.py", line 578, in execute_command
    connection.send_command(*args)
  File "/home/yg/.local/lib/python2.7/site-packages/redis/connection.py", line 563, in send_command
    self.send_packed_command(self.pack_command(*args))
  File "/home/yg/.local/lib/python2.7/site-packages/redis/connection.py", line 538, in send_packed_command
    self.connect()
  File "/home/yg/.local/lib/python2.7/site-packages/redis/connection.py", line 442, in connect
    raise ConnectionError(self._error_message(e))
ConnectionError: Error 111 connecting to localhost:8888. Connection refused.

**Comment by power255** [comment]
yg@yg-VirtualBox:~/py/proxy_pool-master/Run$ python -V
Python 2.7.14
yg@yg-VirtualBox:~/py/proxy_pool-master/Run$ cat /proc/version 
Linux version 4.13.0-16-generic (buildd@lcy01-02) (gcc version 7.2.0 (Ubuntu 7.2.0-8ubuntu2)) #19-Ubuntu SMP Wed Oct 11 18:35:14 UTC 2017

**Comment by jhao104** [comment]
@power255 `ConnectionError: Error 111 connecting to localhost:8888. Connection refused.` 这是你数据库配置不对
