### ISSUE TITLE
Site www.data5u.com timeout

### ISSUE THREAD

**Issue by weaming** [jhao104/proxy_pool#82]
```
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "../Schedule/ProxyRefreshSchedule.py", line 96, in run
    main()
  File "../Schedule/ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "../Manager/ProxyManager.py", line 45, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "../ProxyGetter/getFreeProxy.py", line 53, in freeProxyFirst
    html_tree = getHtmlTree(url)
  File "../Util/utilFunction.py", line 66, in getHtmlTree
    html = wr.get(url=url, header=header).content
AttributeError: 'NoneType' object has no attribute 'content'
```
Then all seems stopped?

**Comment by jhao104** [comment]
annotation the `freeProxyFirst` option in `Config.ini` https://github.com/jhao104/proxy_pool/blob/e3b454e2d2fed0690e71f9aba89739ffa3ffa94f/Config.ini#L11
