### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by DBDB666** [jhao104/proxy_pool#94]
请问这个是由于什么原因导致的，如何修复，谢谢。

```
ERROR:apscheduler.executors.default:Job "main (trigger: interval[0:10:00], next run at: 2017-12-09 13:00:16 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Program Files\Python36\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "..\Schedule\ProxyRefreshSchedule.py", line 80, in main
    p.refresh()
  File "..\Manager\ProxyManager.py", line 45, in refresh
    for proxy in getattr(GetFreeProxy, proxyGetter.strip())():
  File "..\ProxyGetter\getFreeProxy.py", line 127, in freeProxyFifth
    port = each_proxy.xpath(".//span[contains(@class, 'port')]/text()")[0]
IndexError: list index out of range
```

**Comment by jhao104** [comment]
@DBDB666  采集方法出错了，可能是代理网站改版了吧。`ProxyGetter/getFreeProxy.py`的`freeProxyFifth`这个方法有问题，你把`ProxyGetter/getFreeProxy.py`里面注释打开，单独运行测试下这个方法吧，不会修改代码的话在Config.ini，里面把`freeProxyFifth`注释掉，就不会调用它

**Comment by DBDB666** [comment]
@jhao104 谢谢，这个问题不是每次都出现，我试着查看看哪个网站出了问题。

还有一个问题请教，我再ubuntu上部署的时候，已经安装好redis，main.py也跑了起来，这一块都正常，和windows中正常，config.ini中按照教程设置，但是在浏览器中一直是无法打开，请问在linux中还有其他需要设置的地方吗？谢谢

**Comment by jhao104** [comment]
@DBDB666 最好是API和schedule分开运行，文档里面有说， 
不能访问的话，先看启动日志有没有报错，如果启动没问题的话看下防火墙是不是屏蔽了web的端口(5010)

**Comment by DBDB666** [comment]
@jhao104 好的，谢谢，我把防火墙关了，还是没能成功。

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
