### ISSUE TITLE
大家有遇到日志问题吗？把utilFunction.log删除之后就好了，过段时间又有这个错误

### ISSUE THREAD

**Issue by renjhchn** [jhao104/proxy_pool#96]
Logged from file utilFunction.py, line 103
Traceback (most recent call last):
  File "C:\Python27\lib\logging\handlers.py", line 77, in emit
    self.doRollover()
  File "C:\Python27\lib\logging\handlers.py", line 350, in doRollover
2017-12-15 09:09:27,240 ProxyRefreshSchedule.py[line:62] INFO ProxyRefreshSchedule: 58.251.233.31:8270 validation pass
    os.rename(self.baseFilename, dfn)
WindowsError: [Error 32] 
Logged from file utilFunction.py, line 103

**Comment by luaaaa** [comment]
https://github.com/luaaaa/video
